apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: InfrastructureProvider
metadata:
  name: kubevirt
spec:
  # https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt
  version: v0.1.10-infraprovider
  fetchConfig:
    selector:
      matchLabels:
        infraprovider-components: cozy
