// Code generated by values-gen. DO NOT EDIT.
// +kubebuilder:object:generate=true
// +groupName=apps.cozystack.io
// +versionName=v1alpha1
package vpc

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +kubebuilder:object:root=true
type Config struct {
	v1.TypeMeta   `json:",inline"`
	v1.ObjectMeta `json:"metadata,omitempty"`
	Spec          ConfigSpec `json:"spec,omitempty"`
}

type ConfigSpec struct {
	// Subnets of a VPC
	// +kubebuilder:default:={}
	Subnets []Subnet `json:"subnets,omitempty"`
	// VPC peering connections (bidirectional declaration required)
	// +kubebuilder:default:={}
	Peers []Peer `json:"peers,omitempty"`
	// Static routes for the VPC
	// +kubebuilder:default:={}
	Routes []Route `json:"routes,omitempty"`
}

type Peer struct {
	// Namespace of the remote tenant
	TenantNamespace string `json:"tenantNamespace"`
	// Logical name of the remote VPC (without "virtualprivatecloud-" prefix)
	VpcName string `json:"vpcName"`
}

type Route struct {
	// Destination CIDR
	Cidr string `json:"cidr"`
	// Next hop IP address
	NextHopIP string `json:"nextHopIP"`
}

type Subnet struct {
	// Additional source CIDRs admitted into this private subnet, such as remote networks routed in through a gateway VM
	AllowSubnets []string `json:"allowSubnets,omitempty"`
	// IP address range
	Cidr string `json:"cidr,omitempty"`
	// Subnet name
	Name string `json:"name"`
}
