{{- $cozyConfig := lookup "v1" "ConfigMap" "cozy-system" "cozystack" }}
{{- $clusterDomain := (index $cozyConfig.data "cluster-domain") | default "cozy.local" }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (printf "%s-credentials" .Release.Name) }}
{{- $passwords := dict }}

{{- with (dig "data" (dict) $existingSecret) }}
  {{- range $k, $v := . }}
    {{- $_ := set $passwords $k (b64dec $v) }}
  {{- end }}
{{- end }}

{{- range $user, $u := .Values.users }}
  {{- if $u.password }}
    {{- $_ := set $passwords $user $u.password }}
  {{- else if not (index $passwords $user) }}
    {{- $_ := set $passwords $user (randAlphaNum 16) }}
  {{- end }}
{{- end }}

{{- if .Values.users }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-credentials
stringData:
  {{- range $user, $u := .Values.users }}
  {{ quote $user }}: {{ quote (index $passwords $user) }}
  {{- end }}
{{- end }}

---

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ .Release.Name }}-system
spec:
  chart:
    spec:
      chart: cozy-nats
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
      version: '>= 0.0.0-0'
  interval: 5m
  timeout: 10m
  install:
    remediation:
      retries: -1
  upgrade:
    force: true
    remediation:
      retries: -1
  values:
    nats:
      container:
        merge:
          resources: {{- include "cozy-lib.resources.defaultingSanitize" (list .Values.resourcesPreset .Values.resources $) | nindent 12 }}
      fullnameOverride: {{ .Release.Name }}
      config:
        {{- if or $passwords .Values.config.merge }}
        merge:
          {{- if $passwords }}
          accounts:
            A:
              users:
                {{- range $username, $password := $passwords }}
                - user: "{{ $username }}"
                  password: "{{ $password }}"
                {{- end }}
          {{- end }}
          {{- with .Values.config.merge }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- end }}
        {{- with .Values.config.resolver }}
        resolver:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        cluster:
          enabled: true
          routeURLs:
            k8sClusterDomain: {{ $clusterDomain }}
          replicas: {{ .Values.replicas }}
        monitor:
          enabled: true
        jetstream:
          enabled: true
          fileStore:
            enabled: {{ .Values.jetstream.enabled }}
            pvc:
              enabled: true
              size: {{ .Values.jetstream.size }}
              {{- with .Values.storageClass }}
              storageClassName: {{ . }}
              {{- end }}
      promExporter:
        enabled: true
        podMonitor:
          enabled: true
      {{- if .Values.external }}
      service:
        merge:
          spec:
            type: LoadBalancer
      {{- end }}
