// Code generated by values-gen. DO NOT EDIT.
// +kubebuilder:object:generate=true
// +groupName=apps.cozystack.io
// +versionName=v1alpha1
package kubernetes

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	k8sRuntime "k8s.io/apimachinery/pkg/runtime"
)

// +kubebuilder:object:root=true
type Config struct {
	v1.TypeMeta   `json:",inline"`
	v1.ObjectMeta `json:"metadata,omitempty"`
	Spec          ConfigSpec `json:"spec,omitempty"`
}

type ConfigSpec struct {
	// Default StorageClass inside the tenant cluster. Remote-accessible LINSTOR classes are auto-propagated to the tenant under the same name.
	// +kubebuilder:default:="replicated"
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="storageClass is immutable"
	StorageClass string `json:"storageClass"`
	// Kubernetes major.minor version to deploy
	// +kubebuilder:default:="v1.35"
	Version Version `json:"version"`
	// External hostname for Kubernetes cluster. Defaults to `<cluster-name>.<tenant-host>` if empty.
	// +kubebuilder:default:=""
	Host string `json:"host"`
	// Which infrastructure provider backs this cluster's worker VMs. `kubevirt` runs them inside this cluster; `proxmox` runs them on an external Proxmox VE cluster through capmox. The control plane is Kamaji either way — this selects the infrastructure half only. Must match the `substrate` of every KubernetesNodes pool attached to this cluster: the pools reference this cluster's infrastructure object by kind, and a mismatch leaves their Machines unreconciled. Switching an existing cluster is not supported; create a new one.
	// +kubebuilder:default:="kubevirt"
	Substrate string `json:"substrate"`
	// Proxmox substrate settings.
	// +kubebuilder:default:={}
	Proxmox Proxmox `json:"proxmox"`
	// Cluster addons configuration.
	// +kubebuilder:default:={}
	Addons Addons `json:"addons"`
	// Kubernetes control-plane configuration.
	// +kubebuilder:default:={}
	ControlPlane ControlPlane `json:"controlPlane"`
	// Optional image overrides for air-gapped or rate-limited registries.
	// +kubebuilder:default:={}
	Images Images `json:"images"`
	// Talos worker image configuration.
	// +kubebuilder:default:={}
	Talos Talos `json:"talos"`
	// OIDC authentication and per-user RBAC for the tenant kube-apiserver. See docs/oidc-tenant.md for the operator guide.
	// +kubebuilder:default:={}
	Oidc OIDC `json:"oidc"`
}

type APIServer struct {
	// Extra command-line flags appended to the tenant kube-apiserver, passed through to KamajiControlPlane `spec.apiServer.extraArgs`. For OIDC use `spec.oidc.mode` — this passthrough is the escape hatch for other apiserver flags (`--requestheader-uid-headers=X-Remote-Uid`, feature gates, etc). Do NOT add legacy `--oidc-*` flags here when `spec.oidc.mode` is not `None`; the chart injects `--authentication-config` and the apiserver refuses to boot with both. Empty by default (no change to current behavior).
	// +kubebuilder:default:={}
	ExtraArgs []string `json:"extraArgs,omitempty"`
	// Extra volume mounts added to the tenant kube-apiserver container, passed through to KamajiControlPlane `spec.apiServer.extraVolumeMounts`. Each `name` must reference a volume declared in `extraVolumes`; the chart-managed talos secret volumes cannot be mounted. Each item is a core/v1 VolumeMount. Empty by default.
	// +kubebuilder:default:={}
	ExtraVolumeMounts []k8sRuntime.RawExtension `json:"extraVolumeMounts,omitempty"`
	// Extra volumes added to the control-plane Deployment, passed through to KamajiControlPlane `spec.deployment.extraVolumes`. Use to mount a ConfigMap or Secret holding an AuthenticationConfiguration file referenced by `extraArgs`. Each item is a core/v1 Volume, but because the control-plane pod runs on the management cluster only `configMap` and `secret` sources are allowed (host-reaching sources like `hostPath`/`csi` and token-projection via `projected` are rejected); each volume must have a unique, non-empty name and exactly one source. The names `talos-ca` and `talos-tls-cert` are reserved by the chart. Empty by default.
	// +kubebuilder:default:={}
	ExtraVolumes []k8sRuntime.RawExtension `json:"extraVolumes,omitempty"`
	// CPU and memory resources for API Server.
	// +kubebuilder:default:={}
	Resources Resources `json:"resources"`
	// Preset if `resources` omitted.
	// +kubebuilder:default:="c1.medium"
	ResourcesPreset ResourcesPreset `json:"resourcesPreset"`
}

type Addons struct {
	// Cert-manager addon.
	// +kubebuilder:default:={}
	CertManager CertManagerAddon `json:"certManager"`
	// Cilium CNI plugin.
	// +kubebuilder:default:={}
	Cilium CiliumAddon `json:"cilium"`
	// CoreDNS addon.
	// +kubebuilder:default:={}
	Coredns CoreDNSAddon `json:"coredns"`
	// Gateway API addon.
	// +kubebuilder:default:={}
	GatewayAPI GatewayAPIAddon `json:"gatewayAPI"`
	// NVIDIA GPU Operator.
	// +kubebuilder:default:={}
	GpuOperator GPUOperatorAddon `json:"gpuOperator"`
	// HAMi GPU virtualization middleware.
	// +kubebuilder:default:={}
	Hami HAMiAddon `json:"hami"`
	// Ingress-NGINX controller.
	// +kubebuilder:default:={}
	IngressNginx IngressNginxAddon `json:"ingressNginx"`
	// Monitoring agents.
	// +kubebuilder:default:={}
	MonitoringAgents MonitoringAgentsAddon `json:"monitoringAgents"`
	// Hairpin-NAT fix for ingress-nginx with PROXY-protocol.
	// +kubebuilder:default:={}
	Ouroboros OuroborosAddon `json:"ouroboros"`
	// Velero backup/restore addon.
	// +kubebuilder:default:={}
	Velero VeleroAddon `json:"velero"`
	// Vertical Pod Autoscaler.
	// +kubebuilder:default:={}
	VerticalPodAutoscaler VerticalPodAutoscalerAddon `json:"verticalPodAutoscaler"`
}

type CertManagerAddon struct {
	// Enable cert-manager.
	// +kubebuilder:default:=false
	Enabled bool `json:"enabled"`
	// Custom Helm values overrides.
	// +kubebuilder:default:={}
	ValuesOverride k8sRuntime.RawExtension `json:"valuesOverride"`
}

type CiliumAddon struct {
	// Custom Helm values overrides.
	// +kubebuilder:default:={}
	ValuesOverride k8sRuntime.RawExtension `json:"valuesOverride"`
}

type ControlPlane struct {
	// API Server configuration.
	// +kubebuilder:default:={}
	ApiServer APIServer `json:"apiServer"`
	// Controller Manager configuration.
	// +kubebuilder:default:={}
	ControllerManager ControllerManager `json:"controllerManager"`
	// Konnectivity configuration.
	// +kubebuilder:default:={}
	Konnectivity Konnectivity `json:"konnectivity"`
	// Number of control-plane replicas.
	// +kubebuilder:default:=2
	Replicas int `json:"replicas"`
	// Scheduler configuration.
	// +kubebuilder:default:={}
	Scheduler Scheduler `json:"scheduler"`
}

type ControllerManager struct {
	// CPU and memory resources for Controller Manager.
	// +kubebuilder:default:={}
	Resources Resources `json:"resources"`
	// Preset if `resources` omitted.
	// +kubebuilder:default:="t1.micro"
	ResourcesPreset ResourcesPreset `json:"resourcesPreset"`
}

type CoreDNSAddon struct {
	// Custom Helm values overrides.
	// +kubebuilder:default:={}
	ValuesOverride k8sRuntime.RawExtension `json:"valuesOverride"`
}

type GPUOperatorAddon struct {
	// Enable GPU Operator.
	// +kubebuilder:default:=false
	Enabled bool `json:"enabled"`
	// Custom Helm values overrides.
	// +kubebuilder:default:={}
	ValuesOverride k8sRuntime.RawExtension `json:"valuesOverride"`
}

type GatewayAPIAddon struct {
	// Enable Gateway API.
	// +kubebuilder:default:=false
	Enabled bool `json:"enabled"`
}

type HAMiAddon struct {
	// Enable HAMi (requires GPU Operator).
	// +kubebuilder:default:=false
	Enabled bool `json:"enabled"`
	// Custom Helm values overrides.
	// +kubebuilder:default:={}
	ValuesOverride k8sRuntime.RawExtension `json:"valuesOverride"`
}

type Images struct {
	// Image used by the bootstrap-token tenant Job (kubectl). Empty falls back to images/kubectl.tag.
	// +kubebuilder:default:=""
	Kubectl string `json:"kubectl,omitempty"`
	// Image used by the talos-csr-signer sidecar in the Kamaji control plane. Empty falls back to images/talos-csr-signer.tag.
	// +kubebuilder:default:=""
	TalosCsrSigner string `json:"talosCsrSigner,omitempty"`
	// Image used by the wait-for-kubeconfig init container. Empty falls back to images/busybox.tag.
	// +kubebuilder:default:=""
	WaitForKubeconfig string `json:"waitForKubeconfig,omitempty"`
}

type IngressNginxAddon struct {
	// Enable the controller (requires nodes labeled `ingress-nginx`).
	// +kubebuilder:default:=false
	Enabled bool `json:"enabled"`
	// Method to expose the controller. Allowed values: `Proxied`, `LoadBalancer`.
	// +kubebuilder:default:="Proxied"
	ExposeMethod IngressNginxExposeMethod `json:"exposeMethod"`
	// Domains routed to this tenant cluster when `exposeMethod` is `Proxied`.
	// +kubebuilder:default:={}
	Hosts []string `json:"hosts,omitempty"`
	// Custom Helm values overrides.
	// +kubebuilder:default:={}
	ValuesOverride k8sRuntime.RawExtension `json:"valuesOverride"`
}

type Konnectivity struct {
	// Konnectivity Server configuration.
	// +kubebuilder:default:={}
	Server KonnectivityServer `json:"server"`
}

type KonnectivityServer struct {
	// CPU and memory resources for Konnectivity.
	// +kubebuilder:default:={}
	Resources Resources `json:"resources"`
	// Preset if `resources` omitted.
	// +kubebuilder:default:="t1.micro"
	ResourcesPreset ResourcesPreset `json:"resourcesPreset"`
}

type MonitoringAgentsAddon struct {
	// Enable monitoring agents.
	// +kubebuilder:default:=false
	Enabled bool `json:"enabled"`
	// Custom Helm values overrides.
	// +kubebuilder:default:={}
	ValuesOverride k8sRuntime.RawExtension `json:"valuesOverride"`
}

type OIDC struct {
	// Tenant-supplied AuthenticationConfiguration; consumed only when `mode: CustomConfig`.
	// +kubebuilder:default:={}
	CustomConfig OIDCCustomConfig `json:"customConfig,omitempty"`
	// Identity mode. `None`: no OIDC, only the static admin kubeconfig works. `System`: trust the platform `cozy` realm via a per-cluster public client with audience binding; zero-config default. `CustomConfig`: trust a tenant-supplied issuer directly (BYO); `cozy` is not in the path.
	// +kubebuilder:default:="None"
	Mode OIDCMode `json:"mode"`
	// Users granted access to the tenant cluster; each entry produces one ClusterRoleBinding inside the tenant cluster. Works for both `System` and `CustomConfig` modes.
	// +kubebuilder:default:={}
	Users []OIDCUser `json:"users,omitempty"`
}

type OIDCCustomConfig struct {
	// Inline AuthenticationConfiguration YAML (`apiserver.config.k8s.io/v1beta1`). The chart writes the value verbatim into a Secret mounted at `/etc/kubernetes/authentication-config/config.yaml` on the kube-apiserver. Mutually exclusive with `secretRef.name`.
	// +kubebuilder:default:=""
	Config string `json:"config,omitempty"`
	// Reference to an existing Secret in the tenant namespace carrying the `AuthenticationConfiguration`.
	// +kubebuilder:default:={}
	SecretRef OIDCSecretRef `json:"secretRef,omitempty"`
}

type OIDCSecretRef struct {
	// Name of an existing Secret in the tenant (release) namespace whose `config.yaml` key holds an `apiserver.config.k8s.io/v1beta1` `AuthenticationConfiguration`. Mutually exclusive with `customConfig.config`.
	// +kubebuilder:default:=""
	Name string `json:"name,omitempty"`
}

type OIDCUser struct {
	// Email address matched against the `email` claim from the issuer. Used verbatim as the `User:` subject in the ClusterRoleBinding inside the tenant cluster. The `email` claim is a built-in OIDC scope requested explicitly by the chart-generated `kubectl oidc-login` kubeconfig; every conformant OIDC provider (cozy realm included) emits it.
	Email string `json:"email"`
	// Role to bind: `admin` maps to `ClusterRole/cluster-admin`, `view` maps to `ClusterRole/view`.
	Role OIDCRole `json:"role"`
}

type OuroborosAddon struct {
	// Enable ouroboros. Requires addons.ingressNginx.enabled (chart-render fail otherwise). Only useful when PROXY-protocol is wired on the tenant ingress-nginx via valuesOverride.
	// +kubebuilder:default:=false
	Enabled bool `json:"enabled"`
	// Custom Helm values overrides. Operator-key wins over cozystack defaults.
	// +kubebuilder:default:={}
	ValuesOverride k8sRuntime.RawExtension `json:"valuesOverride"`
}

type Proxmox struct {
	// Proxmox nodes capmox may place VMs on. Empty means every node in the Proxmox cluster.
	// +kubebuilder:default:={}
	AllowedNodes []string `json:"allowedNodes,omitempty"`
	// Proxmox cloud-controller-manager settings.
	// +kubebuilder:default:={}
	Ccm ProxmoxCCM `json:"ccm"`
	// Proxmox CSI driver settings.
	// +kubebuilder:default:={}
	Csi ProxmoxCSI `json:"csi"`
	// Nameservers written into each worker's network config. Required by the ProxmoxCluster schema.
	// +kubebuilder:default:={}
	DnsServers []string `json:"dnsServers,omitempty"`
	// Skip verification of the Proxmox API server certificate in the CCM and the CSI driver. Default true because a stock Proxmox VE install serves a self-signed certificate; set false once the hypervisor presents one the tenant can verify.
	// +kubebuilder:default:=true
	Insecure bool `json:"insecure"`
	// Address pool for workers. capmox assigns static addresses and has no DHCP mode, so this is required rather than optional.
	// +kubebuilder:default:={}
	Ipv4Config ProxmoxIPv4 `json:"ipv4Config"`
}

type ProxmoxCCM struct {
	// Secret in THIS namespace holding the controller's Proxmox API credentials under the keys `url`, `token_id`, `token_secret` and `region`. May name the same Secret as `csi.credentialsSecretName`; it is a separate knob so the two can hold separate tokens, since this one only reads VM inventory while the driver attaches and detaches disks.
	// +kubebuilder:default:=""
	CredentialsSecretName string `json:"credentialsSecretName"`
}

type ProxmoxCSI struct {
	// Secret in THIS namespace holding the driver's Proxmox API credentials under the keys `url`, `token_id`, `token_secret` and `region`. Flux injects them into the tenant release, so the token is never written into a rendered manifest. Distinct from the capmox credentials on purpose: the driver attaches and detaches disks, which is a different blast radius from creating VMs.
	// +kubebuilder:default:=""
	CredentialsSecretName string `json:"credentialsSecretName"`
	// Install the driver. Without it a Proxmox-backed tenant has no way to provision PersistentVolumes at all.
	// +kubebuilder:default:=true
	Enabled bool `json:"enabled"`
	// StorageClasses to create in the tenant.
	// +kubebuilder:default:={}
	StorageClasses []ProxmoxStorageClass `json:"storageClasses,omitempty"`
}

type ProxmoxIPv4 struct {
	// Ranges or CIDRs, e.g. `["10.0.0.120-10.0.0.170"]`. capmox turns these into an InClusterIPPool, so they must not overlap any DHCP range on the same L2 or two workers will answer to one address.
	// +kubebuilder:default:={}
	Addresses []string `json:"addresses,omitempty"`
	// Default gateway for the workers.
	// +kubebuilder:default:=""
	Gateway string `json:"gateway"`
	// Netmask prefix length.
	// +kubebuilder:default:=24
	Prefix int `json:"prefix"`
}

type ProxmoxStorageClass struct {
	// Filesystem the driver formats volumes with: ext4 or xfs.
	Fstype string `json:"fstype,omitempty"`
	// StorageClass name inside the tenant cluster.
	Name string `json:"name"`
	// Delete or Retain.
	ReclaimPolicy string `json:"reclaimPolicy,omitempty"`
	// Mark volumes as SSD-backed, which changes the discard/cache defaults Proxmox applies.
	Ssd bool `json:"ssd,omitempty"`
	// Proxmox storage id the volumes are created on (as it appears in `pvesm status`).
	Storage string `json:"storage"`
}

type Resources struct {
	// CPU available.
	Cpu resource.Quantity `json:"cpu,omitempty"`
	// Memory (RAM) available.
	Memory resource.Quantity `json:"memory,omitempty"`
}

type Scheduler struct {
	// CPU and memory resources for Scheduler.
	// +kubebuilder:default:={}
	Resources Resources `json:"resources"`
	// Preset if `resources` omitted.
	// +kubebuilder:default:="t1.micro"
	ResourcesPreset ResourcesPreset `json:"resourcesPreset"`
}

type Talos struct {
	// Base URL of the Talos Image Factory that serves the worker OS disk image (the `openstack-amd64.raw.xz` raw artifact streamed in by CDI over HTTP). Defaults to the public factory. Point at a self-hosted Image Factory, a caching mirror, or an internal HTTP file server for air-gapped, rate-limited, or flaky-egress environments. No trailing slash.
	// +kubebuilder:default:="https://factory.talos.dev"
	ImageFactoryURL string `json:"imageFactoryURL"`
	// OCI repository prefix for the Talos installer image used by the in-guest `talos-reconcile` upgrade Job. Resolved as `<installerRepository>/<schematicID>:<version>`. Defaults to the public factory's installer path. Override for air-gapped or mirrored registries. No trailing slash.
	// +kubebuilder:default:="factory.talos.dev/installer"
	InstallerRepository string `json:"installerRepository"`
	// Talos `machine.registries.mirrors` passthrough for worker nodes: a map of upstream registry host to `{ endpoints: [ ... ] }`. Empty by default, so workers pull container images (the Talos `kubelet` image included) directly from the upstream registry. Point a host such as `ghcr.io` at an in-cluster pull-through mirror for air-gapped, rate-limited, or flaky-egress environments so a worker's boot does not depend on live public egress. Talos still falls back to the upstream registry unless a host also sets `skipFallback: true`, so a mirror alone does not enforce air-gap.
	// +kubebuilder:default:={}
	RegistryMirrors k8sRuntime.RawExtension `json:"registryMirrors"`
	// Talos image-factory schematic ID. Defaults to the cozystack-tested vanilla schematic. Operators using custom schematics (system extensions, kernel args) override here.
	// +kubebuilder:default:="ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515"
	SchematicID string `json:"schematicID"`
	// Talos release used for worker OS image and installer. Must satisfy the chart's Talos<->Kubernetes support matrix against the chosen `version`.
	// +kubebuilder:default:="v1.13.6"
	Version string `json:"version"`
}

type VeleroAddon struct {
	// Enable Velero.
	// +kubebuilder:default:=false
	Enabled bool `json:"enabled"`
	// Custom Helm values overrides.
	// +kubebuilder:default:={}
	ValuesOverride k8sRuntime.RawExtension `json:"valuesOverride"`
}

type VerticalPodAutoscalerAddon struct {
	// Custom Helm values overrides.
	// +kubebuilder:default:={}
	ValuesOverride k8sRuntime.RawExtension `json:"valuesOverride"`
}

// +kubebuilder:validation:Enum="Proxied";"LoadBalancer"
type IngressNginxExposeMethod string

// +kubebuilder:validation:Enum="None";"System";"CustomConfig"
type OIDCMode string

// +kubebuilder:validation:Enum="admin";"view"
type OIDCRole string

// +kubebuilder:validation:Enum="t1.nano";"t1.micro";"t1.small";"t1.medium";"t1.large";"t1.xlarge";"t1.2xlarge";"t1.4xlarge";"c1.nano";"c1.micro";"c1.small";"c1.medium";"c1.large";"c1.xlarge";"c1.2xlarge";"c1.4xlarge";"s1.nano";"s1.micro";"s1.small";"s1.medium";"s1.large";"s1.xlarge";"s1.2xlarge";"s1.4xlarge";"u1.nano";"u1.micro";"u1.small";"u1.medium";"u1.large";"u1.xlarge";"u1.2xlarge";"u1.4xlarge";"m1.nano";"m1.micro";"m1.small";"m1.medium";"m1.large";"m1.xlarge";"m1.2xlarge";"m1.4xlarge";"nano";"micro";"small";"medium";"large";"xlarge";"2xlarge"
type ResourcesPreset string

// +kubebuilder:validation:Enum="v1.35";"v1.34";"v1.33";"v1.32";"v1.31"
type Version string
