//go:build !ignore_autogenerated

/*
Copyright 2025 The Cozystack Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package kubernetes

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIServer) DeepCopyInto(out *APIServer) {
	*out = *in
	if in.ExtraArgs != nil {
		in, out := &in.ExtraArgs, &out.ExtraArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExtraVolumeMounts != nil {
		in, out := &in.ExtraVolumeMounts, &out.ExtraVolumeMounts
		*out = make([]runtime.RawExtension, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExtraVolumes != nil {
		in, out := &in.ExtraVolumes, &out.ExtraVolumes
		*out = make([]runtime.RawExtension, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIServer.
func (in *APIServer) DeepCopy() *APIServer {
	if in == nil {
		return nil
	}
	out := new(APIServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Addons) DeepCopyInto(out *Addons) {
	*out = *in
	in.CertManager.DeepCopyInto(&out.CertManager)
	in.Cilium.DeepCopyInto(&out.Cilium)
	in.Coredns.DeepCopyInto(&out.Coredns)
	in.Fluxcd.DeepCopyInto(&out.Fluxcd)
	out.GatewayAPI = in.GatewayAPI
	in.GpuOperator.DeepCopyInto(&out.GpuOperator)
	in.Hami.DeepCopyInto(&out.Hami)
	in.IngressNginx.DeepCopyInto(&out.IngressNginx)
	in.MonitoringAgents.DeepCopyInto(&out.MonitoringAgents)
	in.Ouroboros.DeepCopyInto(&out.Ouroboros)
	in.Velero.DeepCopyInto(&out.Velero)
	in.VerticalPodAutoscaler.DeepCopyInto(&out.VerticalPodAutoscaler)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Addons.
func (in *Addons) DeepCopy() *Addons {
	if in == nil {
		return nil
	}
	out := new(Addons)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerAddon) DeepCopyInto(out *CertManagerAddon) {
	*out = *in
	in.ValuesOverride.DeepCopyInto(&out.ValuesOverride)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerAddon.
func (in *CertManagerAddon) DeepCopy() *CertManagerAddon {
	if in == nil {
		return nil
	}
	out := new(CertManagerAddon)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CiliumAddon) DeepCopyInto(out *CiliumAddon) {
	*out = *in
	in.ValuesOverride.DeepCopyInto(&out.ValuesOverride)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CiliumAddon.
func (in *CiliumAddon) DeepCopy() *CiliumAddon {
	if in == nil {
		return nil
	}
	out := new(CiliumAddon)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Config) DeepCopyInto(out *Config) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Config.
func (in *Config) DeepCopy() *Config {
	if in == nil {
		return nil
	}
	out := new(Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Config) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigSpec) DeepCopyInto(out *ConfigSpec) {
	*out = *in
	if in.NodeGroups != nil {
		in, out := &in.NodeGroups, &out.NodeGroups
		*out = make(map[string]NodeGroup, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	in.Addons.DeepCopyInto(&out.Addons)
	in.ControlPlane.DeepCopyInto(&out.ControlPlane)
	out.Images = in.Images
	in.Talos.DeepCopyInto(&out.Talos)
	out.NodeHealthCheck = in.NodeHealthCheck
	in.Oidc.DeepCopyInto(&out.Oidc)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigSpec.
func (in *ConfigSpec) DeepCopy() *ConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlane) DeepCopyInto(out *ControlPlane) {
	*out = *in
	in.ApiServer.DeepCopyInto(&out.ApiServer)
	in.ControllerManager.DeepCopyInto(&out.ControllerManager)
	in.Konnectivity.DeepCopyInto(&out.Konnectivity)
	in.Scheduler.DeepCopyInto(&out.Scheduler)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlane.
func (in *ControlPlane) DeepCopy() *ControlPlane {
	if in == nil {
		return nil
	}
	out := new(ControlPlane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerManager) DeepCopyInto(out *ControllerManager) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerManager.
func (in *ControllerManager) DeepCopy() *ControllerManager {
	if in == nil {
		return nil
	}
	out := new(ControllerManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoreDNSAddon) DeepCopyInto(out *CoreDNSAddon) {
	*out = *in
	in.ValuesOverride.DeepCopyInto(&out.ValuesOverride)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoreDNSAddon.
func (in *CoreDNSAddon) DeepCopy() *CoreDNSAddon {
	if in == nil {
		return nil
	}
	out := new(CoreDNSAddon)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FluxCDAddon) DeepCopyInto(out *FluxCDAddon) {
	*out = *in
	in.ValuesOverride.DeepCopyInto(&out.ValuesOverride)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FluxCDAddon.
func (in *FluxCDAddon) DeepCopy() *FluxCDAddon {
	if in == nil {
		return nil
	}
	out := new(FluxCDAddon)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPU) DeepCopyInto(out *GPU) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPU.
func (in *GPU) DeepCopy() *GPU {
	if in == nil {
		return nil
	}
	out := new(GPU)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUOperatorAddon) DeepCopyInto(out *GPUOperatorAddon) {
	*out = *in
	in.ValuesOverride.DeepCopyInto(&out.ValuesOverride)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUOperatorAddon.
func (in *GPUOperatorAddon) DeepCopy() *GPUOperatorAddon {
	if in == nil {
		return nil
	}
	out := new(GPUOperatorAddon)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayAPIAddon) DeepCopyInto(out *GatewayAPIAddon) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayAPIAddon.
func (in *GatewayAPIAddon) DeepCopy() *GatewayAPIAddon {
	if in == nil {
		return nil
	}
	out := new(GatewayAPIAddon)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAMiAddon) DeepCopyInto(out *HAMiAddon) {
	*out = *in
	in.ValuesOverride.DeepCopyInto(&out.ValuesOverride)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAMiAddon.
func (in *HAMiAddon) DeepCopy() *HAMiAddon {
	if in == nil {
		return nil
	}
	out := new(HAMiAddon)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Images) DeepCopyInto(out *Images) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Images.
func (in *Images) DeepCopy() *Images {
	if in == nil {
		return nil
	}
	out := new(Images)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressNginxAddon) DeepCopyInto(out *IngressNginxAddon) {
	*out = *in
	if in.Hosts != nil {
		in, out := &in.Hosts, &out.Hosts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.ValuesOverride.DeepCopyInto(&out.ValuesOverride)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressNginxAddon.
func (in *IngressNginxAddon) DeepCopy() *IngressNginxAddon {
	if in == nil {
		return nil
	}
	out := new(IngressNginxAddon)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Konnectivity) DeepCopyInto(out *Konnectivity) {
	*out = *in
	in.Server.DeepCopyInto(&out.Server)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Konnectivity.
func (in *Konnectivity) DeepCopy() *Konnectivity {
	if in == nil {
		return nil
	}
	out := new(Konnectivity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonnectivityServer) DeepCopyInto(out *KonnectivityServer) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonnectivityServer.
func (in *KonnectivityServer) DeepCopy() *KonnectivityServer {
	if in == nil {
		return nil
	}
	out := new(KonnectivityServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kubelet) DeepCopyInto(out *Kubelet) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kubelet.
func (in *Kubelet) DeepCopy() *Kubelet {
	if in == nil {
		return nil
	}
	out := new(Kubelet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringAgentsAddon) DeepCopyInto(out *MonitoringAgentsAddon) {
	*out = *in
	in.ValuesOverride.DeepCopyInto(&out.ValuesOverride)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringAgentsAddon.
func (in *MonitoringAgentsAddon) DeepCopy() *MonitoringAgentsAddon {
	if in == nil {
		return nil
	}
	out := new(MonitoringAgentsAddon)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeGroup) DeepCopyInto(out *NodeGroup) {
	*out = *in
	out.DiskSize = in.DiskSize.DeepCopy()
	if in.Gpus != nil {
		in, out := &in.Gpus, &out.Gpus
		*out = make([]GPU, len(*in))
		copy(*out, *in)
	}
	out.Kubelet = in.Kubelet
	out.PodCpuLimit = in.PodCpuLimit.DeepCopy()
	out.PodCpuRequest = in.PodCpuRequest.DeepCopy()
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeGroup.
func (in *NodeGroup) DeepCopy() *NodeGroup {
	if in == nil {
		return nil
	}
	out := new(NodeGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeHealthCheck) DeepCopyInto(out *NodeHealthCheck) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeHealthCheck.
func (in *NodeHealthCheck) DeepCopy() *NodeHealthCheck {
	if in == nil {
		return nil
	}
	out := new(NodeHealthCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDC) DeepCopyInto(out *OIDC) {
	*out = *in
	out.CustomConfig = in.CustomConfig
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make([]OIDCUser, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDC.
func (in *OIDC) DeepCopy() *OIDC {
	if in == nil {
		return nil
	}
	out := new(OIDC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCCustomConfig) DeepCopyInto(out *OIDCCustomConfig) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCCustomConfig.
func (in *OIDCCustomConfig) DeepCopy() *OIDCCustomConfig {
	if in == nil {
		return nil
	}
	out := new(OIDCCustomConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCSecretRef) DeepCopyInto(out *OIDCSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCSecretRef.
func (in *OIDCSecretRef) DeepCopy() *OIDCSecretRef {
	if in == nil {
		return nil
	}
	out := new(OIDCSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCUser) DeepCopyInto(out *OIDCUser) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCUser.
func (in *OIDCUser) DeepCopy() *OIDCUser {
	if in == nil {
		return nil
	}
	out := new(OIDCUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OuroborosAddon) DeepCopyInto(out *OuroborosAddon) {
	*out = *in
	in.ValuesOverride.DeepCopyInto(&out.ValuesOverride)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OuroborosAddon.
func (in *OuroborosAddon) DeepCopy() *OuroborosAddon {
	if in == nil {
		return nil
	}
	out := new(OuroborosAddon)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Resources) DeepCopyInto(out *Resources) {
	*out = *in
	out.Cpu = in.Cpu.DeepCopy()
	out.Memory = in.Memory.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Resources.
func (in *Resources) DeepCopy() *Resources {
	if in == nil {
		return nil
	}
	out := new(Resources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Scheduler) DeepCopyInto(out *Scheduler) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Scheduler.
func (in *Scheduler) DeepCopy() *Scheduler {
	if in == nil {
		return nil
	}
	out := new(Scheduler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Talos) DeepCopyInto(out *Talos) {
	*out = *in
	in.RegistryMirrors.DeepCopyInto(&out.RegistryMirrors)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Talos.
func (in *Talos) DeepCopy() *Talos {
	if in == nil {
		return nil
	}
	out := new(Talos)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VeleroAddon) DeepCopyInto(out *VeleroAddon) {
	*out = *in
	in.ValuesOverride.DeepCopyInto(&out.ValuesOverride)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VeleroAddon.
func (in *VeleroAddon) DeepCopy() *VeleroAddon {
	if in == nil {
		return nil
	}
	out := new(VeleroAddon)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerticalPodAutoscalerAddon) DeepCopyInto(out *VerticalPodAutoscalerAddon) {
	*out = *in
	in.ValuesOverride.DeepCopyInto(&out.ValuesOverride)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerticalPodAutoscalerAddon.
func (in *VerticalPodAutoscalerAddon) DeepCopy() *VerticalPodAutoscalerAddon {
	if in == nil {
		return nil
	}
	out := new(VerticalPodAutoscalerAddon)
	in.DeepCopyInto(out)
	return out
}
