apiVersion: apps/v1
kind: Deployment
metadata:
  name: cozystack-controller
  labels:
    app: cozystack-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cozystack-controller
  template:
    metadata:
      labels:
        app: cozystack-controller
    spec:
      serviceAccountName: cozystack-controller
      containers:
      - name: cozystack-controller
        image: "{{ .Values.cozystackController.image }}"
        args:
        - --cozystack-version={{ .Values.cozystackController.cozystackVersion }}
        {{- if .Values.cozystackController.debug }}
        - --zap-log-level=debug
        {{- else }}
        - --zap-log-level=info
        {{- end }}
        {{- if .Values.cozystackController.disableTelemetry }}
        - --disable-telemetry
        {{- end }}
        ports:
        - name: webhook
          containerPort: 9443
        volumeMounts:
          - name: webhook-certs
            mountPath: /tmp/k8s-webhook-server/serving-certs
            readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: cozystack-controller-webhook-cert
            defaultMode: 0400
