kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cozystack-controller
rules:
- apiGroups: [""]
  resources: ["configmaps", "pods", "namespaces", "nodes", "services", "persistentvolumes", "persistentvolumeclaims"]
  verbs: ["get", "watch", "list"]
- apiGroups: ['cozystack.io']
  resources: ['*']
  verbs: ['*']
