kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cozystack-controller
rules:
- apiGroups: ['cozystack.io', 'dashboard.cozystack.io']
  resources: ['*']
  verbs: ['*']
- apiGroups: ["helm.toolkit.fluxcd.io"]
  resources: ["helmreleases"]
  verbs: ["get", "list", "watch", "patch", "update"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch", "patch", "update"]
- apiGroups: ['*']
  resources: ['*']
  verbs: ["get", "list", "watch"]
