apiVersion: v2
name: kafka
description: Managed Kafka service
icon: /logos/kafka.svg
type: application
version: 0.0.0 # Placeholder, the actual version will be automatically set during the build process
appVersion: "3.7.0"
