## @section Common Parameters

## @param storageClass {string} StorageClass used to store the data
storageClass: replicated

## @section Application-specific parameters
## @param version {string} Kubernetes version given as vMAJOR.MINOR. Available are versions from 1.28 to 1.33.
version: "v1.32"
## @param host {string} Hostname used to access the Kubernetes cluster externally. Defaults to `<cluster-name>.<tenant-host>` when empty.
host: ""

## @param nodeGroups {map[string]node} Worker nodes configuration
## @field node {node} Node configuration
## @field node.minReplicas {int} Minimum amount of replicas
## @field node.maxReplicas {int} Maximum amount of replicas
## @field node.instanceType {string} Virtual machine instance type
## @field node.ephemeralStorage {quantity} Ephemeral storage size
## @field node.roles {[]string} List of node's roles
## @field node.resources {resources} Resources available to each worker node
## @field resources.cpu {*quantity} CPU available to each worker node
## @field resources.memory {*quantity} Memory (RAM) available to each worker node
## @field node.gpus {[]gpu} List of GPUs to attach (WARN: NVIDIA driver requires at least 4 GiB of RAM)
## @field gpu.name {string} Name of GPU, such as "nvidia.com/AD102GL_L40S"
##
nodeGroups:
  md0:
    minReplicas: 0
    maxReplicas: 10
    instanceType: "u1.medium"
    ephemeralStorage: 20Gi
    roles:
    - ingress-nginx
    resources: {}
    ## List of GPUs to attach (WARN: NVIDIA driver requires at least 4 GiB of RAM)
    ## e.g:
    ## instanceType: "u1.xlarge"
    ## gpus:
    ## - name: nvidia.com/AD102GL_L40S
    gpus: []


## @section Cluster Addons
##
## @param addons {addons} Cluster addons configuration
addons:
  ## @field addons.certManager {certManager} Cert-manager: automatically creates and manages SSL/TLS certificate
  ##
  certManager:
    ## @field certManager.enabled {bool} Enable cert-manager, which automatically creates and manages SSL/TLS certificates.
    enabled: false
    ## @field certManager.valuesOverride {object} Custom values to override
    valuesOverride: {}

  ## @field addons.cilium {cilium} Cilium CNI plugin
  ##
  cilium:
    ## @field cilium.valuesOverride {object} Custom values to override
    valuesOverride: {}

  ## @field addons.gatewayAPI {gatewayAPI} Gateway API
  ##
  gatewayAPI:
    ## @field gatewayAPI.enabled {bool} Enable the Gateway API
    enabled: false

  ## @field addons.ingressNginx {ingressNginx} Ingress-NGINX Controller
  ##
  ingressNginx:
    ## @field ingressNginx.enabled {bool} Enable the Ingress-NGINX controller (requires nodes labeled with the 'ingress-nginx' role).
    enabled: false
    ## @field ingressNginx.exposeMethod {string enum:"Proxied,LoadBalancer"} Method to expose the Ingress-NGINX controller. Allowed values: `Proxied`, `LoadBalancer`.
    exposeMethod: Proxied
    ## @field ingressNginx.hosts {[]string} List of domain names that the parent cluster should route to this tenant cluster. Taken into account only when `exposeMethod` is set to `Proxied`.
    ## e.g:
    ## hosts:
    ## - example.org
    ## - foo.example.net
    ##
    hosts: []
    ## @field ingressNginx.valuesOverride {object} Custom values to override
    valuesOverride: {}

  ## @field addons.gpuOperator {gpuOperator} GPU-operator: NVIDIA GPU Operator
  ##
  gpuOperator:
    ## @field gpuOperator.enabled {bool} Enable the GPU-operator
    ## @field gpuOperator.valuesOverride {object} Custom values to override
    enabled: false
    valuesOverride: {}

  ## @field addons.fluxcd {fluxcd} Flux CD
  ##
  fluxcd:
    ## @field fluxcd.enabled {bool} Enable FluxCD
    ## @field fluxcd.valuesOverride {object} Custom values to override
    ##
    enabled: false
    valuesOverride: {}

  ## @field addons.monitoringAgents {monitoringAgents} MonitoringAgents
  ##
  monitoringAgents:
    ## @field monitoringAgents.enabled {bool} Enable monitoring agents (Fluent Bit and VMAgents) to send logs and metrics. If tenant monitoring is enabled, data is sent to tenant storage; otherwise, it goes to root storage.
    ## @field monitoringAgents.valuesOverride {object} Custom values to override
    ##
    enabled: false
    valuesOverride: {}

  ## @field addons.verticalPodAutoscaler {verticalPodAutoscaler} VerticalPodAutoscaler
  ##
  verticalPodAutoscaler:
    ## @field verticalPodAutoscaler.valuesOverride {object} Custom values to override
    ##
    valuesOverride: {}

  ## @field addons.velero {velero} Velero
  ##
  velero:
    ## @field velero.enabled {bool} Enable Velero for backup and recovery of a tenant Kubernetes cluster.
    ## @field velero.valuesOverride {object} Custom values to override
    ##
    enabled: false
    valuesOverride: {}

  ## @field addons.coredns {coredns} Coredns
  ##
  coredns:
    ## @field coredns.valuesOverride {object} Custom values to override
    ##
    valuesOverride: {}

## @section Kubernetes Control Plane Configuration
##
## @param controlPlane {controlPlane} Control Plane Configuration
controlPlane:
  ## @field controlPlane.replicas {int} Number of replicas for Kubernetes control plane components.
  replicas: 2
  ## @field controlPlane.apiServer {apiServer} Control plane API server configuration.
  apiServer:
    ## @field apiServer.resources {resources} Explicit CPU and memory configuration for the API Server. When left empty, the preset defined in `resourcesPreset` is applied.
    ## e.g:
    ## resources:
    ##   cpu: 4000m
    ##   memory: 4Gi
    ##
    resources: {}
    ## @field apiServer.resourcesPreset {string enum:"nano,micro,small,medium,large,xlarge,2xlarge"} Default sizing preset used when `resources` is omitted. Allowed values: `nano`, `micro`, `small`, `medium`, `large`, `xlarge`, `2xlarge`.
    resourcesPreset: "medium"

  ## @field controlPlane.controllerManager {controllerManager} Controller Manager configuration.
  controllerManager:
    ## @field controllerManager.resources {resources} Explicit CPU and memory configuration for the Controller Manager. When left empty, the preset defined in `resourcesPreset` is applied.
    ## @field controllerManager.resourcesPreset {string enum:"nano,micro,small,medium,large,xlarge,2xlarge"} Default sizing preset used when `resources` is omitted. Allowed values: `nano`, `micro`, `small`, `medium`, `large`, `xlarge`, `2xlarge`.
    resourcesPreset: "micro"
    resources: {}

  ## @field controlPlane.scheduler {scheduler} Scheduler configuration.
  scheduler:
    ## @field scheduler.resources {resources} Explicit CPU and memory configuration for the Scheduler. When left empty, the preset defined in `resourcesPreset` is applied.
    ## @field scheduler.resourcesPreset {string enum:"nano,micro,small,medium,large,xlarge,2xlarge"} Default sizing preset used when `resources` is omitted. Allowed values: `nano`, `micro`, `small`, `medium`, `large`, `xlarge`, `2xlarge`.
    resourcesPreset: "micro"
    resources: {}

  ## @field controlPlane.konnectivity {konnectivity} Konnectivity configuration.
  konnectivity:
    ## @field konnectivity.server {konnectivityServer} Konnectivity server configuration.
    server:
      ## @field konnectivityServer.resources {resources} Explicit CPU and memory configuration for Konnectivity. When left empty, the preset defined in `resourcesPreset` is applied.
      ## @field konnectivityServer.resourcesPreset {string enum:"nano,micro,small,medium,large,xlarge,2xlarge"} Default sizing preset used when `resources` is omitted. Allowed values: `nano`, `micro`, `small`, `medium`, `large`, `xlarge`, `2xlarge`.
      resourcesPreset: "micro"
      resources: {}
