## @section Common parameters

## @param host The hostname used to access the Kubernetes cluster externally (defaults to using the cluster name as a subdomain for the tenant host).
## @param controlPlane.replicas Number of replicas for Kubernetes contorl-plane components
##
host: ""
controlPlane:
  replicas: 2

## @param nodeGroups [object] nodeGroups configuration
##
nodeGroups:
  md0:
    minReplicas: 0
    maxReplicas: 10
    resources:
      cpu: 2
      memory: 1024Mi
    roles:
    - ingress-nginx

addons:
  ## @param addons.certManager.enabled Enables the certificate manager which automatically creates and manages SSL/TLS certificates
  certManager:
    enabled: true

  ## @param addons.ingressNginx.enabled Enables Ingress-NGINX Controller on nodes with 'ingress-nginx' role
  ## @param addons.ingressNginx.host The domain name that should be passtrough to the cluster by upper ingress.
  ingressNginx:
    enabled: true
    host: "example.org"
