## @section Common parameters
##
## @param replicas {int} Number of VPN server replicas
replicas: 2
## @param resources {*resources} Explicit CPU and memory configuration for each VPN server replica.  When left empty, the preset defined in `resourcesPreset` is applied.
## @field resources.cpu {*quantity} CPU available to each replica
## @field resources.memory {*quantity} Memory (RAM) available to each replica
resources: {}
# resources:
#   cpu: 4000m
#   memory: 4Gi
##
## @param resourcesPreset {string enum:"nano,micro,small,medium,large,xlarge,2xlarge"} Default sizing preset used when `resources` is omitted. Allowed values: `nano`, `micro`, `small`, `medium`, `large`, `xlarge`, `2xlarge`.
resourcesPreset: "nano"
## @param external {bool} Enable external access from outside the cluster
external: false


## @section Application-specific parameters
##
## @param host {string} Host used to substitute into generated URLs
host: ""

## @param users {map[string]user} Users configuration
## @field user.password {*string} Password for the user, autogenerated if none provided
## Example:
## users:
##   user1:
##     password: hackme
##   user2: {} # autogenerated password
users: {}

## @param externalIPs {[]*string} List of externalIPs for service. Optional. If not specified will use LoadBalancer service by default.
## 
## e.g:
## externalIPs:
##   - "11.22.33.44"
##   - "11.22.33.45"
##   - "11.22.33.46"
##
externalIPs: []

