// Code generated by values-gen. DO NOT EDIT.
// +kubebuilder:object:generate=true
// +groupName=apps.cozystack.io
// +versionName=v1alpha1
package vminstance

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +kubebuilder:object:root=true
type Config struct {
	v1.TypeMeta   `json:",inline"`
	v1.ObjectMeta `json:"metadata,omitempty"`
	Spec          ConfigSpec `json:"spec,omitempty"`
}

type ConfigSpec struct {
	// Enable external access from outside the cluster.
	// +kubebuilder:default:=false
	External bool `json:"external"`
	// Method to pass through traffic to the VM.
	// +kubebuilder:default:="PortList"
	ExternalMethod ExternalMethod `json:"externalMethod"`
	// Ports to forward from outside the cluster.
	// +kubebuilder:default:={22}
	ExternalPorts []int `json:"externalPorts,omitempty"`
	// Whether to accept ICMP traffic to the VM in PortList mode (preserves ping and PMTU discovery). No effect in WholeIP mode. Default true so ping behaves as users expect even when port filtering is in effect.
	// +kubebuilder:default:=true
	ExternalAllowICMP bool `json:"externalAllowICMP"`
	// Requested running state of the VirtualMachineInstance
	// +kubebuilder:default:="Always"
	RunStrategy RunStrategy `json:"runStrategy"`
	// Virtual Machine instance type.
	// +kubebuilder:default:="u1.medium"
	InstanceType string `json:"instanceType"`
	// Virtual Machine preferences profile.
	// +kubebuilder:default:="ubuntu"
	InstanceProfile string `json:"instanceProfile"`
	// List of disks to attach.
	// +kubebuilder:default:={}
	Disks []Disk `json:"disks,omitempty"`
	// Networks to attach the VM to.
	// +kubebuilder:default:={}
	Networks []Network `json:"networks,omitempty"`
	// Deprecated: use networks instead.
	// +kubebuilder:default:={}
	Subnets []Network `json:"subnets,omitempty"`
	// List of GPUs to attach (NVIDIA driver requires at least 4 GiB RAM).
	// +kubebuilder:default:={}
	Gpus []GPU `json:"gpus,omitempty"`
	// Model specifies the CPU model inside the VMI. List of available models https://github.com/libvirt/libvirt/tree/master/src/cpu_map
	// +kubebuilder:default:=""
	CpuModel string `json:"cpuModel"`
	// Firmware and boot configuration (UEFI/BIOS selection, Secure Boot, persistent EFI NVRAM).
	// +kubebuilder:default:={}
	Firmware Firmware `json:"firmware,omitempty"`
	// Resource configuration for the virtual machine.
	// +kubebuilder:default:={}
	Resources Resources `json:"resources,omitempty"`
	// List of SSH public keys for authentication.
	// +kubebuilder:default:={}
	SshKeys []string `json:"sshKeys,omitempty"`
	// Cloud-init user data.
	// +kubebuilder:default:=""
	CloudInit string `json:"cloudInit"`
	// Seed string to generate SMBIOS UUID for the VM.
	// +kubebuilder:default:=""
	CloudInitSeed string `json:"cloudInitSeed"`
}

type Disk struct {
	// Disk bus type (e.g. "sata").
	Bus string `json:"bus,omitempty"`
	// Disk name.
	Name string `json:"name"`
}

type Firmware struct {
	// Bootloader to boot the VM with: "uefi" (OVMF) or "bios" (SeaBIOS). Empty inherits the instanceProfile default.
	Bootloader string `json:"bootloader,omitempty"`
	// Persist EFI NVRAM (e.g. enrolled Secure Boot keys, such as an updated Microsoft UEFI CA) across reboots. Only applies when bootloader is "uefi". On default RWO storage the VM is node-pinned (no live-migration).
	EfiPersistent bool `json:"efiPersistent,omitempty"`
	// Enable UEFI Secure Boot. Only applies when bootloader is "uefi".
	SecureBoot bool `json:"secureBoot,omitempty"`
}

type GPU struct {
	// The name of the GPU resource to attach.
	Name string `json:"name"`
}

type Network struct {
	// Network attachment name.
	Name string `json:"name,omitempty"`
}

type Resources struct {
	// Number of CPU cores allocated.
	Cpu resource.Quantity `json:"cpu,omitempty"`
	// Amount of memory allocated.
	Memory resource.Quantity `json:"memory,omitempty"`
	// Number of CPU sockets (vCPU topology).
	Sockets resource.Quantity `json:"sockets,omitempty"`
}

// +kubebuilder:validation:Enum="PortList";"WholeIP"
type ExternalMethod string

// +kubebuilder:validation:Enum="Always";"Halted";"Manual";"RerunOnFailure";"Once"
type RunStrategy string
