## @section Common parameters
##
## @param replicas {int} Number of RabbitMQ replicas
replicas: 3
## @param resources {*resources} Explicit CPU and memory configuration for each RabbitMQ replica.  When left empty, the preset defined in `resourcesPreset` is applied.
## @field resources.cpu {*quantity} CPU available to each replica
## @field resources.memory {*quantity} Memory (RAM) available to each replica
# resources:
#   cpu: 4000m
#   memory: 4Gi
resources: {}

## @param resourcesPreset {string enum:"nano,micro,small,medium,large,xlarge,2xlarge"} Default sizing preset used when `resources` is omitted. Allowed values: `nano`, `micro`, `small`, `medium`, `large`, `xlarge`, `2xlarge`.
resourcesPreset: "nano"
## @param size {quantity} Persistent Volume Claim size, available for application data
size: 10Gi
## @param storageClass {string} StorageClass used to store the data
storageClass: ""
## @param external {bool} Enable external access from outside the cluster
external: false


## @section Application-specific parameters
##
## @param users {map[string]user} Users configuration
## @field user.password {*string} Password for the user
## Example:
## users:
##   user1:
##     password: strongpassword
##   user2:
##     password: hackme
##   user3:
##     password: testtest
##
users: {}

## @param vhosts {map[string]vhost} Virtual Hosts configuration
## @field vhost.roles {roles} Virtual host roles list
## @field roles.admin {[]string} List of admin users
## @field roles.readonly {[]string} List of readonly users
##
## Example:
## vhosts:
##   myapp:
##     roles:
##       admin:
##       - user1
##       - user2
##       readonly:
##       - user3
##   test:
##     roles:
##       admin:
##       - user3
vhosts: {}

