## @section Common parameters

## @param external Enable external access from outside the cluster
## @param size Persistent Volume size
## @param replicas Number of RabbitMQ replicas
## @param storageClass StorageClass used to store the data
##
external: false
size: 10Gi
replicas: 3
storageClass: ""

## @section Configuration parameters

## @param users [object] Users configuration
## Example:
## users:
##   user1:
##     password: strongpassword
##   user2:
##     password: hackme
##   user3:
##     password: testtest
##
users: {}

## @param vhosts Virtual Hosts configuration
## Example:
## vhosts:
##   myapp:
##     roles:
##       admin:
##       - user1
##       - user2
##       readonly:
##       - user3
##   test:
##     roles:
##       admin:
##       - user3
vhosts: {}

## @param resources Explicit CPU and memory configuration for each RabbitMQ replica. When left empty, the preset defined in `resourcesPreset` is applied.
resources: {}
 # resources:
 #   cpu: 4000m
 #   memory: 4Gi
 
## @param resourcesPreset Default sizing preset used when `resources` is omitted. Allowed values: none, nano, micro, small, medium, large, xlarge, 2xlarge.
resourcesPreset: "nano"
