package fluxshardoperator

import (
	"slices"
	"testing"

	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/resource"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/util/intstr"
)

// fluxAIODeployment models the relevant shape of the flux-aio "flux"
// Deployment generated by timoni (internal/fluxinstall/manifests/fluxcd.yaml).
func fluxAIODeployment() *appsv1.Deployment {
	return &appsv1.Deployment{
		ObjectMeta: metav1.ObjectMeta{
			Name:      "flux",
			Namespace: "cozy-fluxcd",
			Labels: map[string]string{
				"app.kubernetes.io/name":    "flux",
				"app.kubernetes.io/version": "v2.8.0",
			},
		},
		Spec: appsv1.DeploymentSpec{
			Template: corev1.PodTemplateSpec{
				Spec: corev1.PodSpec{
					HostNetwork:        true,
					DNSPolicy:          corev1.DNSClusterFirstWithHostNet,
					ServiceAccountName: "flux",
					PriorityClassName:  "system-cluster-critical",
					Tolerations: []corev1.Toleration{
						{Key: "node.kubernetes.io/not-ready", Operator: corev1.TolerationOpExists},
					},
					// flux-aio pins itself off one node and to linux nodes; the
					// required podAntiAffinity targets app.kubernetes.io/name=flux
					// (internal/fluxinstall/manifests/fluxcd.yaml).
					Affinity: &corev1.Affinity{
						NodeAffinity: &corev1.NodeAffinity{
							RequiredDuringSchedulingIgnoredDuringExecution: &corev1.NodeSelector{
								NodeSelectorTerms: []corev1.NodeSelectorTerm{{
									MatchExpressions: []corev1.NodeSelectorRequirement{{
										Key:      "kubernetes.io/os",
										Operator: corev1.NodeSelectorOpIn,
										Values:   []string{"linux"},
									}},
								}},
							},
						},
						PodAntiAffinity: &corev1.PodAntiAffinity{
							RequiredDuringSchedulingIgnoredDuringExecution: []corev1.PodAffinityTerm{{
								LabelSelector: &metav1.LabelSelector{
									MatchExpressions: []metav1.LabelSelectorRequirement{{
										Key:      "app.kubernetes.io/name",
										Operator: metav1.LabelSelectorOpIn,
										Values:   []string{"flux"},
									}},
								},
								TopologyKey: "kubernetes.io/hostname",
							}},
						},
					},
					Volumes: []corev1.Volume{
						{Name: "tmp", VolumeSource: corev1.VolumeSource{EmptyDir: &corev1.EmptyDirVolumeSource{}}},
						{Name: "data", VolumeSource: corev1.VolumeSource{EmptyDir: &corev1.EmptyDirVolumeSource{}}},
					},
					Containers: []corev1.Container{
						{Name: "source-controller", Image: "ghcr.io/fluxcd/source-controller:v1.8.0"},
						{
							Name:  "helm-controller",
							Image: "ghcr.io/fluxcd/helm-controller:v1.5.0",
							Args: []string{
								"--watch-all-namespaces",
								"--log-level=info",
								"--enable-leader-election=false",
								"--metrics-addr=:9795",
								"--health-addr=:9796",
								"--watch-label-selector=!sharding.fluxcd.io/key",
								"--concurrent=5",
								"--requeue-dependency=30s",
								"--events-addr=http://localhost:9690",
								"--feature-gates=ExternalArtifact=true",
							},
							Env: []corev1.EnvVar{
								{Name: "SOURCE_CONTROLLER_LOCALHOST", Value: "localhost:9790"},
								{Name: "SOURCE_WATCHER_LOCALHOST", Value: "localhost:9691"},
								// Injected by the installer into hostNetwork
								// workloads (Talos KubePrism endpoint).
								{Name: "KUBERNETES_SERVICE_HOST", Value: "localhost"},
								{Name: "KUBERNETES_SERVICE_PORT", Value: "7445"},
								{Name: "RUNTIME_NAMESPACE", ValueFrom: &corev1.EnvVarSource{
									FieldRef: &corev1.ObjectFieldSelector{FieldPath: "metadata.namespace"},
								}},
								{Name: "TUF_ROOT", Value: "/tmp/.sigstore"},
								// Corporate-proxy env the installer puts on
								// flux-aio; harmless there but hangs a
								// standalone shard at startup.
								{Name: "HTTP_PROXY", Value: "http://proxy.example:3128"},
								{Name: "HTTPS_PROXY", Value: "http://proxy.example:3128"},
								{Name: "NO_PROXY", Value: ".svc"},
								{Name: "http_proxy", Value: "http://proxy.example:3128"},
								{Name: "https_proxy", Value: "http://proxy.example:3128"},
								{Name: "no_proxy", Value: ".svc"},
							},
							VolumeMounts: []corev1.VolumeMount{{Name: "tmp", MountPath: "/tmp"}},
							LivenessProbe: &corev1.Probe{
								ProbeHandler: corev1.ProbeHandler{
									HTTPGet: &corev1.HTTPGetAction{
										Path: "/healthz",
										Port: intstr.FromString("healthz-hc"),
									},
								},
								PeriodSeconds:    10,
								FailureThreshold: 3,
							},
						},
						{Name: "notification-controller", Image: "ghcr.io/fluxcd/notification-controller:v1.8.0"},
					},
				},
			},
		},
	}
}

func TestBuildShardDeployment(t *testing.T) {
	cfg := &Config{
		FluxNamespace:   "cozy-fluxcd",
		ShardCount:      3,
		ShardConcurrent: 9,
		ShardResources: corev1.ResourceRequirements{
			Requests: corev1.ResourceList{corev1.ResourceCPU: resource.MustParse("100m")},
			Limits:   corev1.ResourceList{corev1.ResourceMemory: resource.MustParse("1Gi")},
		},
	}

	dep, err := BuildShardDeployment(fluxAIODeployment(), 2, cfg)
	if err != nil {
		t.Fatal(err)
	}

	if dep.Name != "helm-controller-shard2" || dep.Namespace != "cozy-fluxcd" {
		t.Fatalf("unexpected object meta: %s/%s", dep.Namespace, dep.Name)
	}
	if dep.Labels[ManagedByLabel] != ManagedByValue {
		t.Fatalf("managed-by label missing: %v", dep.Labels)
	}
	if dep.Labels["app.kubernetes.io/version"] != "v2.8.0" {
		t.Fatalf("version label not inherited from flux-aio: %v", dep.Labels)
	}
	if dep.Spec.Strategy.Type != appsv1.RecreateDeploymentStrategyType {
		t.Fatalf("shard rollout must be Recreate, got %s", dep.Spec.Strategy.Type)
	}
	if *dep.Spec.Replicas != 1 {
		t.Fatalf("expected 1 replica, got %d", *dep.Spec.Replicas)
	}

	ps := dep.Spec.Template.Spec
	if ps.HostNetwork || ps.DNSPolicy != corev1.DNSClusterFirst {
		t.Fatalf("host networking must be sanitised away: hostNetwork=%v dnsPolicy=%s", ps.HostNetwork, ps.DNSPolicy)
	}
	if len(ps.Tolerations) != 0 {
		t.Fatalf("flux-aio bootstrap tolerations must be dropped: %v", ps.Tolerations)
	}
	if ps.Affinity != nil && ps.Affinity.PodAntiAffinity != nil {
		t.Fatalf("inherited pod anti-affinity must be stripped so shards can co-locate with flux-aio: %v",
			ps.Affinity.PodAntiAffinity)
	}
	if ps.Affinity == nil || ps.Affinity.NodeAffinity == nil {
		t.Fatalf("benign nodeAffinity (e.g. os=linux) must be preserved: %+v", ps.Affinity)
	}
	if ps.ServiceAccountName != "flux" || ps.PriorityClassName != "system-cluster-critical" {
		t.Fatalf("flux pod identity must be inherited: sa=%s prio=%s", ps.ServiceAccountName, ps.PriorityClassName)
	}
	if len(ps.Containers) != 1 || ps.Containers[0].Name != "helm-controller" {
		t.Fatalf("only the helm-controller container must survive: %v", ps.Containers)
	}
	if len(ps.Volumes) != 1 || ps.Volumes[0].Name != "tmp" {
		t.Fatalf("only volumes mounted by helm-controller must survive: %v", ps.Volumes)
	}

	hc := ps.Containers[0]
	if hc.Image != "ghcr.io/fluxcd/helm-controller:v1.5.0" {
		t.Fatalf("image must be inherited from flux-aio: %s", hc.Image)
	}
	if !slices.Contains(hc.Args, "--watch-label-selector=sharding.fluxcd.io/key=shard2") {
		t.Fatalf("shard watch selector missing: %v", hc.Args)
	}
	if !slices.Contains(hc.Args, "--concurrent=9") {
		t.Fatalf("concurrent override missing: %v", hc.Args)
	}
	if !slices.Contains(hc.Args, "--feature-gates=ExternalArtifact=true") {
		t.Fatalf("unrelated args must be preserved: %v", hc.Args)
	}
	for _, arg := range hc.Args {
		if arg == "--watch-label-selector=!sharding.fluxcd.io/key" ||
			arg == "--concurrent=5" ||
			arg == "--events-addr=http://localhost:9690" {
			t.Fatalf("unsanitised arg leaked through: %s", arg)
		}
	}

	for _, e := range hc.Env {
		switch e.Name {
		case "SOURCE_CONTROLLER_LOCALHOST", "SOURCE_WATCHER_LOCALHOST":
			t.Fatalf("localhost cross-container env leaked through: %s", e.Name)
		case "KUBERNETES_SERVICE_HOST", "KUBERNETES_SERVICE_PORT":
			// A non-hostNetwork pod dialing the node-local KubePrism endpoint
			// crashloops on "dial tcp [::1]:7445: connect: connection refused".
			t.Fatalf("node-local apiserver endpoint env leaked through: %s", e.Name)
		case "HTTP_PROXY", "HTTPS_PROXY", "NO_PROXY",
			"http_proxy", "https_proxy", "no_proxy":
			// A standalone shard behind an unreachable proxy hangs at startup
			// and crashloops before it ever serves /healthz.
			t.Fatalf("corporate-proxy env leaked through: %s", e.Name)
		}
	}
	envNames := make([]string, 0, len(hc.Env))
	for _, e := range hc.Env {
		envNames = append(envNames, e.Name)
	}
	if !slices.Contains(envNames, "RUNTIME_NAMESPACE") || !slices.Contains(envNames, "TUF_ROOT") {
		t.Fatalf("regular env must be preserved: %v", envNames)
	}

	if hc.Resources.Limits.Memory().String() != "1Gi" {
		t.Fatalf("resources override not applied: %v", hc.Resources)
	}

	if hc.StartupProbe == nil {
		t.Fatal("startupProbe must be added so a slow start is not liveness-killed into a crashloop")
	}
	if hc.StartupProbe.HTTPGet == nil || hc.StartupProbe.HTTPGet.Path != "/healthz" {
		t.Fatalf("startupProbe must reuse the liveness /healthz handler: %+v", hc.StartupProbe)
	}
	if hc.StartupProbe.FailureThreshold < 10 {
		t.Fatalf("startupProbe budget too small to cover a slow cache sync: %d", hc.StartupProbe.FailureThreshold)
	}
}

func TestBuildShardDeploymentInheritsResourcesWhenUnset(t *testing.T) {
	flux := fluxAIODeployment()
	flux.Spec.Template.Spec.Containers[1].Resources = corev1.ResourceRequirements{
		Requests: corev1.ResourceList{corev1.ResourceCPU: resource.MustParse("123m")},
	}
	dep, err := BuildShardDeployment(flux, 0, &Config{FluxNamespace: "cozy-fluxcd", ShardConcurrent: 5})
	if err != nil {
		t.Fatal(err)
	}
	if dep.Spec.Template.Spec.Containers[0].Resources.Requests.Cpu().String() != "123m" {
		t.Fatalf("cloned resources must be kept when no override is configured: %v",
			dep.Spec.Template.Spec.Containers[0].Resources)
	}
}

func TestBuildShardDeploymentMergesPartialResourceOverrides(t *testing.T) {
	flux := fluxAIODeployment()
	flux.Spec.Template.Spec.Containers[1].Resources = corev1.ResourceRequirements{
		Requests: corev1.ResourceList{
			corev1.ResourceCPU:    resource.MustParse("123m"),
			corev1.ResourceMemory: resource.MustParse("32Mi"),
		},
		Limits: corev1.ResourceList{corev1.ResourceCPU: resource.MustParse("500m")},
	}
	cfg := &Config{
		FluxNamespace:   "cozy-fluxcd",
		ShardConcurrent: 5,
		ShardResources: corev1.ResourceRequirements{
			Limits: corev1.ResourceList{corev1.ResourceMemory: resource.MustParse("1Gi")},
		},
	}
	dep, err := BuildShardDeployment(flux, 0, cfg)
	if err != nil {
		t.Fatal(err)
	}
	res := dep.Spec.Template.Spec.Containers[0].Resources
	if res.Requests.Cpu().String() != "123m" || res.Requests.Memory().String() != "32Mi" {
		t.Fatalf("cloned requests must survive a limits-only override: %v", res)
	}
	if res.Limits.Cpu().String() != "500m" {
		t.Fatalf("cloned cpu limit must survive a memory-only limits override: %v", res)
	}
	if res.Limits.Memory().String() != "1Gi" {
		t.Fatalf("configured memory limit must be applied: %v", res)
	}
}

func TestBuildShardDeploymentMissingContainer(t *testing.T) {
	flux := fluxAIODeployment()
	flux.Spec.Template.Spec.Containers = flux.Spec.Template.Spec.Containers[:1]
	if _, err := BuildShardDeployment(flux, 0, &Config{FluxNamespace: "cozy-fluxcd"}); err == nil {
		t.Fatal("expected an error when the helm-controller container is missing")
	}
}

func TestParseShardDeploymentIndex(t *testing.T) {
	if idx, ok := ParseShardDeploymentIndex("helm-controller-shard4"); !ok || idx != 4 {
		t.Fatalf("ParseShardDeploymentIndex(helm-controller-shard4) = %d,%v", idx, ok)
	}
	for _, name := range []string{"helm-controller-shard", "flux-tenants", "helm-controller-tenants"} {
		if _, ok := ParseShardDeploymentIndex(name); ok {
			t.Fatalf("ParseShardDeploymentIndex(%s) must fail", name)
		}
	}
}
