
## @section Common parameters

## @param external Enable external access from outside the cluster
## @param size Persistent Volume size
## @param storageClass StorageClass used to store the data
## @param haproxy.replicas Number of HAProxy replicas
## @param nginx.replicas Number of Nginx replicas
##
external: false
size: 10Gi
storageClass: ""
haproxy:
  replicas: 2
  ## @param haproxy.resources Explicit CPU and memory configuration for each HAProxy replica. When left empty, the preset defined in `resourcesPreset` is applied.
  resources: {}
  # resources:
  #   cpu: 4000m
  #   memory: 4Gi

  ## @param haproxy.resourcesPreset Default sizing preset used when `resources` is omitted. Allowed values: none, nano, micro, small, medium, large, xlarge, 2xlarge.
  resourcesPreset: "nano"
nginx:
  replicas: 2
  ## @param nginx.resources Explicit CPU and memory configuration for each nginx replica. When left empty, the preset defined in `resourcesPreset` is applied.
  resources: {}
  # resources:
  #   cpu: 4000m
  #   memory: 4Gi

  ## @param nginx.resourcesPreset Default sizing preset used when `resources` is omitted. Allowed values: none, nano, micro, small, medium, large, xlarge, 2xlarge.
  resourcesPreset: "nano"

## @section Configuration parameters

## @param endpoints Endpoints configuration
## Example:
## endpoints:
##   - 10.100.3.1:80
##   - 10.100.3.11:80
##   - 10.100.3.2:80
##   - 10.100.3.12:80
##   - 10.100.3.3:80
##   - 10.100.3.13:80
##
endpoints: []
