
## @section Common parameters

## @param external Enable external access from outside the cluster
## @param size Persistent Volume size
## @param storageClass StorageClass used to store the data
## @param haproxy.replicas Number of HAProxy replicas
## @param nginx.replicas Number of Nginx replicas
##
external: false
size: 10Gi
storageClass: ""
haproxy:
  replicas: 2
  ## @param haproxy.resources Resources
  resources: {}
  # resources:
  #   limits:
  #     cpu: 4000m
  #     memory: 4Gi
  #   requests:
  #     cpu: 100m
  #     memory: 512Mi
  
  ## @param haproxy.resourcesPreset Set container resources according to one common preset (allowed values: none, nano, micro, small, medium, large, xlarge, 2xlarge). This is ignored if resources is set (resources is recommended for production).
  resourcesPreset: "nano"
nginx:
  replicas: 2
  ## @param nginx.resources Resources
  resources: {}
  # resources:
  #   limits:
  #     cpu: 4000m
  #     memory: 4Gi
  #   requests:
  #     cpu: 100m
  #     memory: 512Mi
  
  ## @param nginx.resourcesPreset Set container resources according to one common preset (allowed values: none, nano, micro, small, medium, large, xlarge, 2xlarge). This is ignored if resources is set (resources is recommended for production).
  resourcesPreset: "nano"

## @section Configuration parameters

## @param endpoints Endpoints configuration
## Example:
## endpoints:
##   - 10.100.3.1:80
##   - 10.100.3.11:80
##   - 10.100.3.2:80
##   - 10.100.3.12:80
##   - 10.100.3.3:80
##   - 10.100.3.13:80
##
endpoints: []
