## @section Common parameters
##
## @param size {quantity} Persistent Volume Claim size, available for application data
size: 10Gi
## @param storageClass {string} StorageClass used to store the data
storageClass: ""
## @param external {bool} Enable external access from outside the cluster
external: false
## @section Application-specific parameters

## @param endpoints {[]string} Endpoints configuration, as a list of <ip:port>
## Example:
## endpoints:
##   - 10.100.3.1:80
##   - 10.100.3.11:80
##   - 10.100.3.2:80
##   - 10.100.3.12:80
##   - 10.100.3.3:80
##   - 10.100.3.13:80
##
endpoints: []


## @section HAProxy parameters
##
## @param haproxy {haproxy} HAProxy configuration
haproxy:
  ## @field haproxy.replicas {int} Number of HAProxy replicas
  replicas: 2
  ## @field haproxy.resources {resources} Explicit CPU and memory configuration for each replica. When left empty, the preset defined in `resourcesPreset` is applied.
  ## @field resources.cpu {*quantity} CPU available to each replica
  ## @field resources.memory {*quantity} Memory (RAM) available to each replica
  resources: {}
  # resources:
  #   cpu: 4000m
  #   memory: 4Gi
  ## @field haproxy.resourcesPreset {string enum:"nano,micro,small,medium,large,xlarge,2xlarge"} Default sizing preset used when `resources` is omitted. Allowed values: `nano`, `micro`, `small`, `medium`, `large`, `xlarge`, `2xlarge`.
  resourcesPreset: "nano"

## @section Nginx parameters
##
## @param nginx {nginx} Nginx configuration
nginx:
  ## @field nginx.replicas {int} Number of Nginx replicas
  replicas: 2
  ## @field nginx.resources {*resources} Explicit CPU and memory configuration for each replica. When left empty, the preset defined in `resourcesPreset` is applied.
  # resources:
  #   cpu: 4000m
  #   memory: 4Gi
  resources: {}

  ## @field nginx.resourcesPreset {string enum:"nano,micro,small,medium,large,xlarge,2xlarge"} Default sizing preset used when `resources` is omitted. Allowed values: `nano`, `micro`, `small`, `medium`, `large`, `xlarge`, `2xlarge`.
  resourcesPreset: "nano"
