repos:
- repo: local
  hooks:
    - id: run-make-generate
      name: Run 'make generate' in all app directories
      entry: |
        flock -x .git/pre-commit.lock sh -c '
          for dir in ./packages/apps/*/ ./packages/extra/*/; do
            if [ -d "$dir" ]; then
              echo "Running make generate in $dir"
              make generate -C "$dir" || exit $?
            fi
          done
          git diff --color=always | cat
        '
      language: system
      files: ^.*$
