{{- if eq .Values.topology "Client" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-objectstorage-provisioner
  namespace: {{ .Release.Namespace }}
automountServiceAccountToken: true
{{- end }}
