---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation,hook-failed
  name: {{ .Release.Name }}-flux-teardown
spec:
  template:
    spec:
      serviceAccountName: {{ .Release.Name }}-flux-teardown
      restartPolicy: Never
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: "NoSchedule"
      containers:
        - name: kubectl
          image: docker.io/clastix/kubectl:v1.32
          command:
            - /bin/sh
            - -c
            - |
                for resource in KeycloakRealmGroup KeycloakClientScope KeycloakClient; do
                  kubectl get "$resource" -A --no-headers -o custom-columns="NAMESPACE:.metadata.namespace,NAME:.metadata.name" | \
                  while read -r namespace name; do
                    kubectl patch "$resource" "$name" -n "$namespace" --type=merge -p '{"metadata":{"finalizers":[]}}'
                  done
                done

                for resource in ClusterKeycloakRealm ClusterKeycloak; do
                  kubectl get "$resource" --no-headers -o custom-columns="NAME:.metadata.name" | \
                  while read -r name; do
                    kubectl patch "$resource" "$name" --type=merge -p '{"metadata":{"finalizers":[]}}'
                  done
                done

                kubectl patch hr keycloak-configure -n cozy-system --type=merge -p '{"metadata":{"finalizers":[]}}'


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-flux-teardown
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-failed
    helm.sh/hook-weight: "0"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    "helm.sh/hook": pre-install,post-install,pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation,hook-failed
    "helm.sh/hook-weight": "5"
  name: {{ .Release.Name }}-flux-teardown
rules:
  - apiGroups:
      - "v1.edp.epam.com"
    resources:
      - keycloakrealmgroups
      - keycloakclientscopes
      - keycloakclients
      - clusterkeycloakrealms
      - clusterkeycloaks
      - keycloakrealms
      - keycloakrealmusers
      - keycloakrealmroles
      - keycloakrealmidentityproviders
      - keycloakrealmcomponents
      - keycloakauthflows
      - keycloaks
    verbs:
      - get
      - list
      - delete
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-flux-teardown
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-flux-teardown
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-flux-teardown
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    "helm.sh/hook": pre-install,post-install,pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation,hook-failed
    "helm.sh/hook-weight": "5"
  name: {{ .Release.Name }}-flux-teardown
rules:
  - apiGroups:
      - "helm.toolkit.fluxcd.io"
    resources:
      - helmreleases
    verbs:
      - get
      - list
      - delete
      - watch
      - patch
    resourceNames:
      - {{ .Release.Name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation,hook-failed
    helm.sh/hook-weight: "5"
  name: {{ .Release.Name }}-flux-teardown
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-flux-teardown
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-flux-teardown
    namespace: {{ .Release.Namespace }}
