apiVersion: apps.cozystack.io/v1alpha1
kind: VMDisk
metadata:
  name: test
spec:
  source:
    http:
      url: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
  optical: false
  storage: 5Gi
  storageClass: ($values.storageClass)
