#!/bin/sh
# Migration 20 --> 21

set -euo pipefail

kubectl delete ingresses.networking.k8s.io --all -n cozy-dashboard --ignore-not-found
kubectl delete crd cozystackresourcedefinitions.cozystack.io --ignore-not-found

# Stamp version
kubectl create configmap -n cozy-system cozystack-version \
  --from-literal=version=21 --dry-run=client -o yaml | kubectl apply -f-
