---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-foundationdb
  labels:
    app.kubernetes.io/name: foundationdb
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}