apiVersion: v1
kind: ConfigMap
metadata:
  name: talos-log-collector
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "talos-log-collector.labels" . | nindent 4 }}
data:
  vector.yaml: |
    data_dir: /vector-data
    sources:
      talos:
        type: socket
        mode: tcp
        address: 0.0.0.0:{{ .Values.listenPort }}
        decoding:
          codec: json
    transforms:
      tag:
        type: remap
        inputs: [talos]
        source: |
          .log_source = "talos_system"
          .node = get_env_var("VECTOR_SELF_NODE_NAME") ?? "unknown"
          .tenant = "{{ .Values.global.target | default "tenant-root" }}"
          .cluster = "root-cluster"
    sinks:
      victorialogs:
        type: http
        inputs: [tag]
        uri: "http://vlinsert-generic.{{ .Values.global.target | default "tenant-root" }}.svc:9481/insert/jsonline?_stream_fields=node,log_source,talos-service,facility,tenant,cluster&_msg_field=msg&_time_field=talos-time"
        method: post
        compression: gzip
        encoding:
          codec: json
        framing:
          method: newline_delimited
        request:
          headers:
            Content-Type: application/x-ndjson
            AccountID: "0"
            ProjectID: "0"
