apiVersion: v1
kind: ServiceAccount
metadata:
  name: talos-log-collector
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "talos-log-collector.labels" . | nindent 4 }}
automountServiceAccountToken: false
