apiVersion: v2
name: cozy-etcd-operator
description: Cozystack etcd-operator (etcd-operator.cozystack.io/v1alpha2) controller-manager
type: application
version: 0.0.0 # Placeholder, the actual version will be automatically set during the build process
appVersion: v0.5.4
