{{- $sourceSecret := lookup "v1" "Secret" "cozy-system" "patch-containerd" }}
{{- if $sourceSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-patch-containerd
  namespace: {{ .Release.Namespace }}
type: {{ $sourceSecret.type }}
data:
{{- range $key, $value := $sourceSecret.data }}
  {{ printf "%s: %s" $key ($value | quote) | indent 2 }}
{{- end }}
{{- end }}
