apiVersion: v1
kind: Service
metadata:
  name: proxmox-network-controller-metrics
  labels:
    app: proxmox-network-controller
spec:
  selector:
    app: proxmox-network-controller
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: proxmox-network-controller
spec:
  selector:
    matchLabels:
      app: proxmox-network-controller
  endpoints:
  - port: metrics
    scheme: http
