apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: proxmox-network-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: proxmox-network-controller
subjects:
- kind: ServiceAccount
  name: proxmox-network-controller
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: proxmox-network-controller-leader-election
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: proxmox-network-controller-leader-election
subjects:
- kind: ServiceAccount
  name: proxmox-network-controller
  namespace: {{ .Release.Namespace }}
