{{- $host := index .Values._cluster "root-host" }}
{{- $realm := index .Values._cluster "oidc-realm-name" | default "cozy" }}
{{- $oidcEnabled := index .Values._cluster "oidc-enabled" }}
{{- if $oidcEnabled }}
{{-   $apiServerEndpoint := index .Values._cluster "api-server-endpoint" }}
{{-   $managementKubeconfigEndpoint := default "" (index .Values._cluster "management-kubeconfig-endpoint") }}
{{-   if and $managementKubeconfigEndpoint (ne $managementKubeconfigEndpoint "") }}
{{-     $apiServerEndpoint = $managementKubeconfigEndpoint }}
{{-   end }}
{{-   $k8sCa := index .Values._cluster "kube-root-ca" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: kubeconfig-{{ .Release.Namespace }}
stringData:
  kubeconfig: |
    apiVersion: v1
    clusters:
    - cluster:
        server: {{ $apiServerEndpoint }}
        certificate-authority-data: {{ $k8sCa }}
      name: cluster
    contexts:
    - context:
        cluster: cluster
        namespace: {{ .Release.Namespace }}
        user: keycloak
      name: {{ .Release.Namespace }}
    current-context: {{ .Release.Namespace }}
    users:
    - name: keycloak
      user:
        exec:
          apiVersion: client.authentication.k8s.io/v1beta1
          args:
          - oidc-login
          - get-token
          - --oidc-issuer-url=https://keycloak.{{ $host }}/realms/{{ $realm }}
          - --oidc-client-id=kubernetes
          - --skip-open-browser
          command: kubectl
{{- end }}
