ingress-nginx:
  controller:
    extraArgs:
      enable-ssl-passthrough: ""
    image:
      registry: ghcr.io
      image: cozystack/ingress-nginx-with-protobuf-exporter/controller
      tag: v1.11.2
      digest: sha256:beba8869ee370599e1f26557a9669ebdc9481c07b34059f348eb3e17b647e7e0
    allowSnippetAnnotations: true
    replicaCount: 2
    admissionWebhooks:
      certManager:
        enabled: true
    metrics:
      enabled: true
    extraContainers:
    - name: protobuf-exporter
      image: ghcr.io/kvaps/ingress-nginx-with-protobuf-exporter/protobuf-exporter:v1.11.2@sha256:6d9235a9ee6f2be1921db4687afbdcd85d145b087dd916b5a96455bdb5cff560
      args:
      - --server.telemetry-address=0.0.0.0:9090
      - --server.exporter-address=0.0.0.0:9091
      resources:
        limits:
          cpu: 100m
          memory: 90Mi
        requests:
          cpu: 100m
          memory: 90Mi
    service:
      #type: NodePort # ClusterIP
      externalTrafficPolicy: "Local"
      #allocateLoadBalancerNodePorts: false
    config:
      ## proxy protocol
      #use-proxy-protocol: "true"
      #use-forwarded-headers: "true"
      #compute-full-forwarded-for: "true"
      #real-ip-header: "proxy_protocol"
      #enable-real-ip: "true"
      # keep-alive
      proxy-connect-timeout: "10"
      proxy-read-timeout: "10"
      keep-alive-requests: "1000000"
      upstream-keepalive-requests: "100000"
      upstream-keepalive-time: '1m'
      upstream-keepalive-timeout: "60"
      upstream-keepalive-connections: "320"
      ssl-session-tickets: "true"
    resources:
      limits:
        cpu: "1"
        memory: 2048Mi
      requests:
        cpu: 100m
        memory: 90Mi

  defaultBackend:
    ##
    enabled: true
    resources:
      limits:
        cpu: 10m
        memory: 20Mi
      requests:
        cpu: 10m
        memory: 20Mi

