ingress-nginx:
  controller:
    extraArgs:
      enable-ssl-passthrough: ""
    image:
      registry: ghcr.io
      image: cozystack/ingress-nginx-with-protobuf-exporter/controller
      tag: v1.11.5
      digest: sha256:b78ae118129a9417d4126744cab2fc2f777b3a9ac460d74caa4b57a479b98ead
    allowSnippetAnnotations: true
    replicaCount: 2
    admissionWebhooks:
      certManager:
        enabled: true
    metrics:
      enabled: true
    extraContainers:
    - name: protobuf-exporter
      image: ghcr.io/cozystack/ingress-nginx-with-protobuf-exporter/protobuf-exporter:v1.11.5@sha256:1e60d53324c2028d6f20136cdd5553ebf2d1288aefc5900b96cd379680fc25dc
      args:
      - --server.telemetry-address=0.0.0.0:9090
      - --server.exporter-address=0.0.0.0:9091
      resources:
        limits:
          cpu: 100m
          memory: 90Mi
        requests:
          cpu: 100m
          memory: 90Mi
    service:
      #type: NodePort # ClusterIP
      externalTrafficPolicy: "Local"
      #allocateLoadBalancerNodePorts: false
    config:
      ## proxy protocol
      #use-proxy-protocol: "true"
      #use-forwarded-headers: "true"
      #compute-full-forwarded-for: "true"
      #real-ip-header: "proxy_protocol"
      #enable-real-ip: "true"
      # keep-alive
      proxy-connect-timeout: "10"
      proxy-read-timeout: "10"
      keep-alive-requests: "1000000"
      upstream-keepalive-requests: "100000"
      upstream-keepalive-time: '1m'
      upstream-keepalive-timeout: "60"
      upstream-keepalive-connections: "320"
      ssl-session-tickets: "true"
    resources:
      limits:
        cpu: "1"
        memory: 2048Mi
      requests:
        cpu: 100m
        memory: 90Mi

  defaultBackend:
    ##
    enabled: true
    resources:
      limits:
        cpu: 10m
        memory: 20Mi
      requests:
        cpu: 10m
        memory: 20Mi
