#!/usr/bin/env bats
# Guards the contract that makes a release publish WITH its changelog.
#
# The release body is no longer written by hand or synced after the fact: it is
# docs/changelogs/vX.Y.Z.md, generated by promote-rc.yaml, committed onto the
# release-X.Y.Z staging branch, carried through the promote PR, and read back by
# pull-requests-release.yaml finalize at publication. That chain spans three
# workflow files and a docs contract, and every link is a plain string — a job
# rename, a moved `if:`, or a reworded prompt breaks it silently, and the failure
# only ever shows up as a published release with empty notes. That is exactly the
# class of bug nobody notices until it is public and irreversible.
#
# The tests below pin the links that are cheap to assert and expensive to lose:
#
#   1. open-pr survives a failed changelog job (the non-blocking guarantee).
#   2. The AI step is the ONLY thing allowed to fail silently.
#   3. finalize reads the changelog file as the release body.
#   4. finalize refuses whitespace-only content rather than blanking the notes.
#   5. The generator is pointed at a checkout state docs/agents/changelog.md
#      actually permits.
#   6. The tags.yaml backstop ports an existing changelog instead of regenerating.
#   7. promote preserves a changelog across the staging-branch force-push.
#   8. The finalize trigger has no paths filter that a docs-only promote PR would
#      trip over.
#
# WHAT THIS DOES NOT CHECK, so a green tick is not mistaken for a working release:
#
#   * That the changelog is CORRECT, or that the AI produces anything at all.
#     Generation quality is unobservable from here and is what review is for.
#   * That GitHub's `needs` / `if:` semantics behave as assumed. These tests pin
#     what the YAML SAYS; whether a skipped upstream job really propagates is
#     GitHub's contract, verifiable only by dispatching a real promotion.
#   * Anything in cozystack/website. The docs job deliberately still runs at tag
#     push (where RELEASE_TAG resolves to a tag that exists) — moving it earlier
#     needs a change in that repo first, and nothing here would catch its absence.
#   * Whether the release body ACTUALLY lands. That is one API call at publish
#     time, on a path no unit test reaches.

REPO_ROOT="$(cd "$(dirname "${BATS_TEST_FILENAME:-$0}")/.." && pwd)"
PROMOTE="$REPO_ROOT/.github/workflows/promote-rc.yaml"
FINALIZE="$REPO_ROOT/.github/workflows/pull-requests-release.yaml"
TAGS="$REPO_ROOT/.github/workflows/tags.yaml"
CHANGELOG_DOC="$REPO_ROOT/docs/agents/changelog.md"

# Body of a single top-level job block in a workflow file, from `  <name>:` up to
# the next top-level job. Keyed on two-space indentation, which is the layout
# every workflow in this repo uses.
job_block() {
  awk -v job="  $1:" '
    $0 == job { inside = 1; next }
    /^  [a-z0-9_-]+:$/ { inside = 0 }
    inside' "$2"
}

@test "all four release workflow files exist" {
  for f in "$PROMOTE" "$FINALIZE" "$TAGS" "$CHANGELOG_DOC"; do
    [ -f "$f" ] || { echo "missing $f" >&2; exit 1; }
  done
}

# 1. The non-blocking guarantee. `needs: [promote, changelog]` alone makes GitHub
#    SKIP open-pr whenever changelog fails, which would leave the staging branch
#    pushed and the release drafted but no promote PR at all — strictly worse than
#    the old flow, where the PR was opened inside promote and nothing about
#    changelog generation could block it. A Copilot or npm outage must degrade to
#    "PR opens without a changelog", never to "no PR".
@test "open-pr opens the promote PR even when the changelog job fails" {
  block="$(job_block open-pr "$PROMOTE")"
  [ -n "$block" ] || { echo "Could not locate the open-pr job in $PROMOTE" >&2; exit 1; }

  printf '%s\n' "$block" | grep -q 'needs: \[promote, changelog\]' || {
    echo "open-pr no longer declares 'needs: [promote, changelog]'." >&2
    exit 1
  }

  # Must not be gated on the changelog job's result.
  printf '%s\n' "$block" | grep -qE '^\s*if:.*!cancelled\(\)' || {
    echo "open-pr has no '!cancelled()' job-level if:. Without one, a failed" >&2
    echo "changelog job SKIPS open-pr and no promote PR is ever opened." >&2
    exit 1
  }
  printf '%s\n' "$block" | grep -qE "^\s*if:.*needs\.promote\.result == 'success'" || {
    echo "open-pr's if: no longer gates on needs.promote.result == 'success'." >&2
    exit 1
  }
  printf '%s\n' "$block" | grep -qE '^\s*if:.*needs\.changelog\.result' && {
    echo "open-pr's job-level if: references needs.changelog.result. Gating the" >&2
    echo "PR on the changelog job re-introduces the wedge this if: exists to prevent." >&2
    exit 1
  }
  return 0
}

# 2. continue-on-error is a blast radius, not a convenience. It belongs on the AI
#    invocation and nowhere else: on a verification or commit step it would let a
#    broken changelog through as if it were fine.
@test "only the AI generation step is allowed to fail silently" {
  block="$(job_block changelog "$PROMOTE")"
  [ -n "$block" ] || { echo "Could not locate the changelog job in $PROMOTE" >&2; exit 1; }

  count="$(printf '%s\n' "$block" | grep -c 'continue-on-error: true' || true)"
  [ "$count" -eq 1 ] || {
    echo "Expected exactly 1 'continue-on-error: true' in the changelog job, found $count." >&2
    echo "Only the 'Generate changelog using AI' step may fail silently — on any other" >&2
    echo "step it would let an unvalidated or missing changelog through unnoticed." >&2
    exit 1
  }

  # The single occurrence must sit in the AI step, not somewhere else.
  ai_step="$(printf '%s\n' "$block" | awk '
    /^      - name: Generate changelog using AI$/ { inside = 1; next }
    /^      - name: / { inside = 0 }
    inside')"
  [ -n "$ai_step" ] || { echo "Could not locate the 'Generate changelog using AI' step" >&2; exit 1; }
  printf '%s\n' "$ai_step" | grep -q 'continue-on-error: true' || {
    echo "'Generate changelog using AI' is not the step carrying continue-on-error." >&2
    exit 1
  }
}

# 3. The load-bearing read. If finalize stops reading the file, releases publish
#    with whatever the draft happened to carry ("Promoted from vX.Y.Z-rc.N.") and
#    the whole point of generating the changelog before publication is lost.
@test "finalize uses the changelog file as the published release body" {
  grep -q 'docs/changelogs/\${tag}\.md' "$FINALIZE" || {
    echo "finalize no longer references docs/changelogs/\${tag}.md." >&2
    echo "The release body would fall back to the draft's placeholder text." >&2
    exit 1
  }
  # The read must actually reach updateRelease.
  grep -qE '\.\.\.\(body \? \{ body \} : \{\}\)' "$FINALIZE" || {
    echo "finalize's updateRelease call no longer conditionally spreads { body }." >&2
    exit 1
  }
}

# 4. A whitespace-only file is worse than no file: it would blank the release
#    notes more thoroughly than publishing the draft body would. promote-rc
#    validates structurally, but a changelog can also arrive by hand-commit, so
#    finalize keeps its own last-line-of-defence check.
@test "finalize refuses an empty or whitespace-only changelog as the body" {
  grep -qE 'raw\.trim\(\)\.length === 0' "$FINALIZE" || {
    echo "finalize no longer guards against a whitespace-only changelog." >&2
    echo "Such a file would publish as blank release notes." >&2
    exit 1
  }
}

# 5. docs/agents/changelog.md section 2 is a hard gate: it enumerates the valid
#    working-tree states and tells the agent to STOP otherwise. The promotion job
#    checks out the rc tag, so that state must be one the doc names — otherwise a
#    COMPLIANT agent refuses to generate anything and the normal path produces no
#    changelog at all, silently, forever.
@test "the promotion checkout state is one docs/agents/changelog.md permits" {
  block="$(job_block changelog "$PROMOTE")"
  printf '%s\n' "$block" | grep -qE 'ref: \$\{\{ steps\.parse\.outputs\.rc_tag \}\}' || {
    echo "The changelog job no longer checks out the rc TAG." >&2
    echo "A staging-branch checkout is a state changelog.md section 2 rejects." >&2
    exit 1
  }
  grep -qi 'release-candidate.* tag being promoted' "$CHANGELOG_DOC" || {
    echo "docs/agents/changelog.md section 2 no longer documents the promotion" >&2
    echo "configuration (detached at the rc tag). A compliant agent would stop." >&2
    exit 1
  }
  # The checkout must never consume raw dispatch input.
  printf '%s\n' "$block" | grep -qE 'ref: \$\{\{ inputs\.rc_tag \}\}' && {
    echo "The changelog job checks out raw inputs.rc_tag instead of the validated" >&2
    echo "parse output — untrusted input reaching actions/checkout's ref." >&2
    exit 1
  }
  return 0
}

# 6. When a promote PR targets release-X.Y (a patch release), the changelog never
#    reaches main, so the backstop fires. It must PORT the reviewed file from the
#    tag, not regenerate: a second AI pass would spend quota and then, once its PR
#    merged, update-releasenotes.yaml would overwrite already-published release
#    notes with text nobody approved.
@test "the tags.yaml backstop ports an existing changelog instead of regenerating" {
  block="$(job_block generate-changelog "$TAGS")"
  [ -n "$block" ] || { echo "Could not locate generate-changelog in $TAGS" >&2; exit 1; }

  printf '%s\n' "$block" | grep -q 'at_tag=true' || {
    echo "The backstop no longer detects a changelog present at the tag commit." >&2
    exit 1
  }

  # Every AI step must be gated on the file being absent at the tag.
  for step in 'Setup Node.js' 'Install GitHub Copilot CLI' 'Generate changelog using AI'; do
    step_block="$(printf '%s\n' "$block" | awk -v s="      - name: $step" '
      $0 == s { inside = 1; next }
      /^      - name: / { inside = 0 }
      inside')"
    [ -n "$step_block" ] || { echo "Could not locate backstop step '$step'" >&2; exit 1; }
    printf '%s\n' "$step_block" | grep -qE "at_tag == 'false'" || {
      echo "Backstop step '$step' is not gated on at_tag == 'false'." >&2
      echo "It would regenerate a changelog that already exists at the tag, and the" >&2
      echo "resulting PR would overwrite published release notes." >&2
      exit 1
    }
  done
}

# 7. The staging branch is rebuilt from the rc tree and force-pushed on every
#    re-dispatch. A changelog committed there by hand (the documented recovery
#    when generation fails) or by an earlier dispatch must survive that, or a
#    retry silently replaces human-edited release notes.
@test "promote preserves an existing changelog across the staging-branch rebuild" {
  block="$(job_block promote "$PROMOTE")"
  [ -n "$block" ] || { echo "Could not locate the promote job in $PROMOTE" >&2; exit 1; }

  printf '%s\n' "$block" | grep -q 'PRESERVED' || {
    echo "The Prepare stable branch step no longer preserves an existing changelog." >&2
    echo "A re-dispatch would force-push away a hand-written one." >&2
    exit 1
  }
  printf '%s\n' "$block" | grep -qE 'git show "FETCH_HEAD:\$\{CL\}"' || {
    echo "The preserve path no longer reads the changelog from the remote staging branch." >&2
    exit 1
  }

  # And open-pr must not clobber what promote preserved.
  open_block="$(job_block open-pr "$PROMOTE")"
  printf '%s\n' "$open_block" | grep -qE "steps\.existing\.outputs\.present == 'false'" || {
    echo "open-pr no longer checks for an existing changelog before downloading the" >&2
    echo "generated artifact — it would overwrite preserved human edits." >&2
    exit 1
  }
}

# 8. The promote PR now carries docs/changelogs/vX.Y.Z.md, and Prepare stable
#    branch tolerates producing no tag-string changes ("digests already stable").
#    Together those can yield a docs-only promote PR. A `paths-ignore: docs/**`
#    on the finalize trigger would drop it: no finalize run, so no tag, no
#    release, and no error raised anywhere.
@test "the finalize trigger has no paths filter that a docs-only promote PR would trip" {
  trigger="$(awk '/^on:/ { inside = 1; next } /^[a-z]/ { inside = 0 } inside' "$FINALIZE")"
  [ -n "$trigger" ] || { echo "Could not locate the on: block in $FINALIZE" >&2; exit 1; }

  printf '%s\n' "$trigger" | grep -qE '^\s*(paths|paths-ignore):' && {
    echo "The finalize trigger declares a paths filter. A promote PR whose only" >&2
    echo "change is the changelog would be filtered out, and the release would" >&2
    echo "never be tagged or published — silently. Filtering belongs in the job's" >&2
    echo "if: gate (merged + release label + bot author), not the trigger." >&2
    exit 1
  }
  return 0
}
