// Code generated by values-gen. DO NOT EDIT.
// +kubebuilder:object:generate=true
// +groupName=apps.cozystack.io
// +versionName=v1alpha1
package vmdisk

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +kubebuilder:object:root=true
type Config struct {
	v1.TypeMeta   `json:",inline"`
	v1.ObjectMeta `json:"metadata,omitempty"`
	Spec          ConfigSpec `json:"spec,omitempty"`
}

type ConfigSpec struct {
	// The source image location used to create a disk.
	// +kubebuilder:default:={}
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="source is immutable"
	Source Source `json:"source"`
	// Defines if disk should be considered optical.
	// +kubebuilder:default:=false
	Optical bool `json:"optical"`
	// The size of the disk allocated for the virtual machine.
	// +kubebuilder:default:="5Gi"
	Storage resource.Quantity `json:"storage"`
	// StorageClass used to store the data.
	// +kubebuilder:default:="replicated"
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="storageClass is immutable"
	StorageClass string `json:"storageClass"`
	// Provision the volume at disk creation instead of waiting for a consumer.
	// +kubebuilder:default:=true
	BindImmediately bool `json:"bindImmediately"`
}

type Source struct {
	// Clone an existing vm-disk.
	Disk *SourceDisk `json:"disk,omitempty"`
	// Download image from an HTTP source.
	Http *SourceHTTP `json:"http,omitempty"`
	// Use image by name from default collection.
	Image *SourceImage `json:"image,omitempty"`
	// Upload local image.
	Upload *SourceUpload `json:"upload,omitempty"`
}

type SourceDisk struct {
	// Name of the vm-disk to clone.
	Name string `json:"name"`
}

type SourceHTTP struct {
	// URL to download the image.
	Url string `json:"url"`
}

type SourceImage struct {
	// Name of the image to use.
	Name string `json:"name"`
}

type SourceUpload struct {
}
