// Code generated by values-gen. DO NOT EDIT.
// +kubebuilder:object:generate=true
// +groupName=apps.cozystack.io
// +versionName=v1alpha1
package harbor

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +kubebuilder:object:root=true
type Config struct {
	v1.TypeMeta   `json:",inline"`
	v1.ObjectMeta `json:"metadata,omitempty"`
	Spec          ConfigSpec `json:"spec,omitempty"`
}

type ConfigSpec struct {
	// Hostname for external access to Harbor (defaults to 'harbor' subdomain for the tenant host).
	// +kubebuilder:default:=""
	Host string `json:"host,omitempty"`
	// IP addresses or CIDR ranges allowed to reach the Harbor web portal and API. `/v2/` and `/service/token`, which `docker login`, image pulls and pushes use, are not restricted by this list. For the portal and API it replaces the tenant ingress `whitelist` rather than narrowing it, and it is matched against the client address the ingress controller sees, which is a proxy or a forwarded header rather than the real client when something in front of the controller rewrites it. Empty allows every address. Requires Ingress publishing; rejected when the tenant publishes through Gateway API.
	// +kubebuilder:default:={}
	ManagementWhitelist []string `json:"managementWhitelist,omitempty"`
	// StorageClass used to store the data.
	// +kubebuilder:default:=""
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="storageClass is immutable"
	StorageClass string `json:"storageClass"`
	// Core API server configuration.
	// +kubebuilder:default:={}
	Core Core `json:"core"`
	// Container image registry configuration.
	// +kubebuilder:default:={}
	Registry Registry `json:"registry"`
	// Background job service configuration.
	// +kubebuilder:default:={}
	Jobservice Jobservice `json:"jobservice"`
	// Trivy vulnerability scanner configuration.
	// +kubebuilder:default:={}
	Trivy Trivy `json:"trivy"`
	// PostgreSQL database configuration.
	// +kubebuilder:default:={}
	Database Database `json:"database"`
	// Redis cache configuration.
	// +kubebuilder:default:={}
	Redis Redis `json:"redis"`
}

type Core struct {
	// Explicit CPU and memory configuration. When omitted, the preset defined in `resourcesPreset` is applied.
	// +kubebuilder:default:={}
	Resources Resources `json:"resources,omitempty"`
	// Default sizing preset used when `resources` is omitted.
	// +kubebuilder:default:="t1.small"
	ResourcesPreset ResourcesPreset `json:"resourcesPreset,omitempty"`
}

type Database struct {
	// Number of database instances.
	// +kubebuilder:default:=2
	Replicas int `json:"replicas"`
	// Persistent Volume size for database storage.
	// +kubebuilder:default:="5Gi"
	Size resource.Quantity `json:"size"`
}

type Jobservice struct {
	// Explicit CPU and memory configuration. When omitted, the preset defined in `resourcesPreset` is applied.
	// +kubebuilder:default:={}
	Resources Resources `json:"resources,omitempty"`
	// Default sizing preset used when `resources` is omitted.
	// +kubebuilder:default:="t1.nano"
	ResourcesPreset ResourcesPreset `json:"resourcesPreset,omitempty"`
}

type Redis struct {
	// Number of Redis replicas.
	// +kubebuilder:default:=2
	Replicas int `json:"replicas"`
	// Persistent Volume size for cache storage.
	// +kubebuilder:default:="1Gi"
	Size resource.Quantity `json:"size"`
}

type Registry struct {
	// Explicit CPU and memory configuration. When omitted, the preset defined in `resourcesPreset` is applied.
	// +kubebuilder:default:={}
	Resources Resources `json:"resources,omitempty"`
	// Default sizing preset used when `resources` is omitted.
	// +kubebuilder:default:="t1.small"
	ResourcesPreset ResourcesPreset `json:"resourcesPreset,omitempty"`
}

type Resources struct {
	// Number of CPU cores allocated.
	Cpu resource.Quantity `json:"cpu,omitempty"`
	// Amount of memory allocated.
	Memory resource.Quantity `json:"memory,omitempty"`
}

type Trivy struct {
	// Enable or disable the vulnerability scanner.
	// +kubebuilder:default:=true
	Enabled bool `json:"enabled"`
	// Explicit CPU and memory configuration. When omitted, the preset defined in `resourcesPreset` is applied.
	// +kubebuilder:default:={}
	Resources Resources `json:"resources,omitempty"`
	// Default sizing preset used when `resources` is omitted.
	// +kubebuilder:default:="t1.nano"
	ResourcesPreset ResourcesPreset `json:"resourcesPreset,omitempty"`
	// Persistent Volume size for vulnerability database cache.
	// +kubebuilder:default:="5Gi"
	Size resource.Quantity `json:"size"`
}

// +kubebuilder:validation:Enum="t1.nano";"t1.micro";"t1.small";"t1.medium";"t1.large";"t1.xlarge";"t1.2xlarge";"t1.4xlarge";"c1.nano";"c1.micro";"c1.small";"c1.medium";"c1.large";"c1.xlarge";"c1.2xlarge";"c1.4xlarge";"s1.nano";"s1.micro";"s1.small";"s1.medium";"s1.large";"s1.xlarge";"s1.2xlarge";"s1.4xlarge";"u1.nano";"u1.micro";"u1.small";"u1.medium";"u1.large";"u1.xlarge";"u1.2xlarge";"u1.4xlarge";"m1.nano";"m1.micro";"m1.small";"m1.medium";"m1.large";"m1.xlarge";"m1.2xlarge";"m1.4xlarge";"nano";"micro";"small";"medium";"large";"xlarge";"2xlarge"
type ResourcesPreset string
