## @section Common parameters

## @param replicas {int} Number of ingress-nginx replicas
##
replicas: 2

## @param whitelist {[]*string} List of client networks
## Example:
## whitelist:
## - "1.2.3.4"
## - "10.100.0.0/16"
whitelist: []

## @param clouflareProxy {bool} Restoring original visitor IPs when Cloudflare proxied is enabled
clouflareProxy: false
