{{- $cozyConfig := lookup "v1" "ConfigMap" "cozy-system" "cozystack" }}
{{- $issuerType := (index $cozyConfig.data "clusterissuer") | default "http01" }}

{{- $myNS := lookup "v1" "Namespace" "" .Release.Namespace }}
{{- $host := index $myNS.metadata.annotations "namespace.cozystack.io/host" }}

{{- if .Values.virtExportProxy }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    cert-manager.io/cluster-issuer: letsencrypt-prod
    {{- if eq $issuerType "cloudflare" }} 
    {{- else }}
    acme.cert-manager.io/http01-ingress-class: {{ .Release.Namespace }}
    {{- end }}
  name: virt-exportproxy-{{ .Release.Namespace }}
  namespace: cozy-kubevirt
spec:
  ingressClassName: {{ .Release.Namespace }}
  rules:
  - host: virt-exportproxy.{{ $host }}
    http:
      paths:
      - backend:
          service:
            name: virt-exportproxy
            port:
              number: 443
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    virt-exportproxy.{{ $host }}
    secretName: virt-exportproxy-{{ .Release.Namespace }}-tls
{{- end }}
