apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: lineage-controller-webhook
  labels:
    app: lineage-controller-webhook
spec:
  selector:
    matchLabels:
      app: lineage-controller-webhook
  template:
    metadata:
      labels:
        app: lineage-controller-webhook
    spec:
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      serviceAccountName: lineage-controller-webhook
      containers:
      - name: lineage-controller-webhook
        image: "{{ .Values.lineageControllerWebhook.image }}"
        args:
        {{- if .Values.lineageControllerWebhook.debug }}
        - --zap-log-level=debug
        {{- else }}
        - --zap-log-level=info
        {{- end }}
        ports:
        - name: webhook
          containerPort: 9443
        volumeMounts:
          - name: webhook-certs
            mountPath: /tmp/k8s-webhook-server/serving-certs
            readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: lineage-controller-webhook-cert
            defaultMode: 0400
