apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lineage-controller-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lineage-controller-webhook
subjects:
- kind: ServiceAccount
  name: lineage-controller-webhook
  namespace: {{ .Release.Namespace }}
