apiVersion: v1
kind: Service
metadata:
  name: lineage-controller-webhook
  labels:
    app: lineage-controller-webhook
spec:
  internalTrafficPolicy: Local
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 9443
      protocol: TCP
      name: webhook
  selector:
    app: lineage-controller-webhook
