flux-operator:
  fullnameOverride: flux-operator
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoSchedule
  hostNetwork: true
  resources:
    limits:
      cpu: 100m
      memory: 350Mi
    requests:
      cpu: 100m
      memory: 350Mi
