//go:build !ignore_autogenerated

/*
Copyright 2025 The Cozystack Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPPoolUsage) DeepCopyInto(out *IPPoolUsage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPPoolUsage.
func (in *IPPoolUsage) DeepCopy() *IPPoolUsage {
	if in == nil {
		return nil
	}
	out := new(IPPoolUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxmoxNetwork) DeepCopyInto(out *ProxmoxNetwork) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxmoxNetwork.
func (in *ProxmoxNetwork) DeepCopy() *ProxmoxNetwork {
	if in == nil {
		return nil
	}
	out := new(ProxmoxNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProxmoxNetwork) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxmoxNetworkList) DeepCopyInto(out *ProxmoxNetworkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProxmoxNetwork, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxmoxNetworkList.
func (in *ProxmoxNetworkList) DeepCopy() *ProxmoxNetworkList {
	if in == nil {
		return nil
	}
	out := new(ProxmoxNetworkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProxmoxNetworkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxmoxNetworkSpec) DeepCopyInto(out *ProxmoxNetworkSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxmoxNetworkSpec.
func (in *ProxmoxNetworkSpec) DeepCopy() *ProxmoxNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(ProxmoxNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxmoxNetworkStatus) DeepCopyInto(out *ProxmoxNetworkStatus) {
	*out = *in
	if in.MTU != nil {
		in, out := &in.MTU, &out.MTU
		*out = new(int32)
		**out = **in
	}
	if in.IPPool != nil {
		in, out := &in.IPPool, &out.IPPool
		*out = new(IPPoolUsage)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxmoxNetworkStatus.
func (in *ProxmoxNetworkStatus) DeepCopy() *ProxmoxNetworkStatus {
	if in == nil {
		return nil
	}
	out := new(ProxmoxNetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxmoxNetworkZone) DeepCopyInto(out *ProxmoxNetworkZone) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxmoxNetworkZone.
func (in *ProxmoxNetworkZone) DeepCopy() *ProxmoxNetworkZone {
	if in == nil {
		return nil
	}
	out := new(ProxmoxNetworkZone)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProxmoxNetworkZone) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxmoxNetworkZoneList) DeepCopyInto(out *ProxmoxNetworkZoneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProxmoxNetworkZone, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxmoxNetworkZoneList.
func (in *ProxmoxNetworkZoneList) DeepCopy() *ProxmoxNetworkZoneList {
	if in == nil {
		return nil
	}
	out := new(ProxmoxNetworkZoneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProxmoxNetworkZoneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxmoxNetworkZoneSpec) DeepCopyInto(out *ProxmoxNetworkZoneSpec) {
	*out = *in
	if in.VLANRanges != nil {
		in, out := &in.VLANRanges, &out.VLANRanges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ReservedVLANs != nil {
		in, out := &in.ReservedVLANs, &out.ReservedVLANs
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
	if in.MTU != nil {
		in, out := &in.MTU, &out.MTU
		*out = new(int32)
		**out = **in
	}
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.StaticAssignments != nil {
		in, out := &in.StaticAssignments, &out.StaticAssignments
		*out = make([]StaticVLANAssignment, len(*in))
		copy(*out, *in)
	}
	if in.Egress != nil {
		in, out := &in.Egress, &out.Egress
		*out = new(ZoneEgress)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxmoxNetworkZoneSpec.
func (in *ProxmoxNetworkZoneSpec) DeepCopy() *ProxmoxNetworkZoneSpec {
	if in == nil {
		return nil
	}
	out := new(ProxmoxNetworkZoneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxmoxNetworkZoneStatus) DeepCopyInto(out *ProxmoxNetworkZoneStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxmoxNetworkZoneStatus.
func (in *ProxmoxNetworkZoneStatus) DeepCopy() *ProxmoxNetworkZoneStatus {
	if in == nil {
		return nil
	}
	out := new(ProxmoxNetworkZoneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StaticVLANAssignment) DeepCopyInto(out *StaticVLANAssignment) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StaticVLANAssignment.
func (in *StaticVLANAssignment) DeepCopy() *StaticVLANAssignment {
	if in == nil {
		return nil
	}
	out := new(StaticVLANAssignment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneEgress) DeepCopyInto(out *ZoneEgress) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneEgress.
func (in *ZoneEgress) DeepCopy() *ZoneEgress {
	if in == nil {
		return nil
	}
	out := new(ZoneEgress)
	in.DeepCopyInto(out)
	return out
}
