// Code generated by values-gen. DO NOT EDIT.
// +kubebuilder:object:generate=true
// +groupName=apps.cozystack.io
// +versionName=v1alpha1
package mongodb

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +kubebuilder:object:root=true
type Config struct {
	v1.TypeMeta   `json:",inline"`
	v1.ObjectMeta `json:"metadata,omitempty"`
	Spec          ConfigSpec `json:"spec,omitempty"`
}

type ConfigSpec struct {
	// Number of MongoDB replicas in replica set.
	// +kubebuilder:default:=3
	Replicas int `json:"replicas"`
	// Explicit CPU and memory configuration for each MongoDB replica. When omitted, the preset defined in `resourcesPreset` is applied.
	// +kubebuilder:default:={}
	Resources Resources `json:"resources,omitempty"`
	// Default sizing preset used when `resources` is omitted.
	// +kubebuilder:default:="t1.small"
	ResourcesPreset ResourcesPreset `json:"resourcesPreset"`
	// Persistent Volume Claim size available for application data.
	// +kubebuilder:default:="10Gi"
	Size resource.Quantity `json:"size"`
	// StorageClass used to store the data.
	// +kubebuilder:default:=""
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="storageClass is immutable"
	StorageClass string `json:"storageClass"`
	// Enable external access from outside the cluster.
	// +kubebuilder:default:=false
	External bool `json:"external"`
	// MongoDB major version to deploy.
	// +kubebuilder:default:="v8"
	Version Version `json:"version"`
	// Enable sharded cluster mode. When disabled, deploys a replica set.
	// +kubebuilder:default:=false
	Sharding bool `json:"sharding"`
	// Configuration for sharded cluster mode.
	// +kubebuilder:default:={}
	ShardingConfig ShardingConfig `json:"shardingConfig"`
	// Users configuration map.
	// +kubebuilder:default:={}
	Users map[string]User `json:"users,omitempty"`
	// Databases configuration map.
	// +kubebuilder:default:={}
	Databases map[string]Database `json:"databases,omitempty"`
	// Backup configuration.
	// +kubebuilder:default:={}
	Backup Backup `json:"backup"`
	// Bootstrap configuration.
	// +kubebuilder:default:={}
	Bootstrap Bootstrap `json:"bootstrap"`
}

type Backup struct {
	// Destination path for backups (e.g. s3://bucket/path/). Ignored when useSystemBucket is true (the driver injects the platform bucket).
	// +kubebuilder:default:="s3://bucket/path/to/folder/"
	DestinationPath string `json:"destinationPath,omitempty"`
	// Enable regular backups.
	// +kubebuilder:default:=false
	Enabled bool `json:"enabled"`
	// S3 endpoint URL for uploads. Ignored when useSystemBucket is true (the strategy supplies the platform endpoint).
	// +kubebuilder:default:="http://minio-gateway-service:9000"
	EndpointURL string `json:"endpointURL,omitempty"`
	// Skip TLS verification for the S3 endpoint (self-signed, e.g. in-cluster seaweedfs). Ignored when useSystemBucket is true (the platform backupStorage knob applies instead).
	// +kubebuilder:default:=false
	InsecureSkipTLSVerify bool `json:"insecureSkipTLSVerify,omitempty"`
	// Retention policy (e.g. "30d"). Ignored when useSystemBucket is true (no engine-side retention on that flow).
	// +kubebuilder:default:="30d"
	RetentionPolicy string `json:"retentionPolicy,omitempty"`
	// Access key for S3 authentication. Ignored when useSystemBucket is true (credentials come from the projected cozy-backups-creds).
	// +kubebuilder:default:=""
	S3AccessKey string `json:"s3AccessKey,omitempty"`
	// Secret key for S3 authentication. Ignored when useSystemBucket is true (credentials come from the projected cozy-backups-creds).
	// +kubebuilder:default:=""
	S3SecretKey string `json:"s3SecretKey,omitempty"`
	// Cron schedule for automated backups. Ignored when useSystemBucket is true (scheduling moves to the BackupClass Plan).
	// +kubebuilder:default:="0 2 * * *"
	Schedule string `json:"schedule,omitempty"`
	// Opt-in: back up to the platform system bucket without supplying S3 credentials. The cozy-default MongoDB BackupClass injects the storage at BackupJob time; tenants do not set s3AccessKey/s3SecretKey/destinationPath/endpointURL, and backups scope to `<namespace>/<application>`. Scheduling moves to a BackupClass Plan; `schedule`, `retentionPolicy` and PITR are ignored while this is on, and this flow has no retention yet (see docs/operations/backup-classes.md). Requires `backup.enabled: true` (the pbm agents run on that flag); the schema rejects the combination with `enabled: false` and the chart refuses it at render time. A release that has not yet rendered this flag (its cluster still carries the chart's scheduled tasks and PITR) holds a BackupJob until it does, so the tenant's own storage is never injected over.
	// +kubebuilder:default:=false
	UseSystemBucket bool `json:"useSystemBucket,omitempty"`
}

type Bootstrap struct {
	// Name of backup to restore from.
	// +kubebuilder:default:=""
	BackupName string `json:"backupName"`
	// Whether to restore from a backup.
	// +kubebuilder:default:=false
	Enabled bool `json:"enabled"`
	// Timestamp for point-in-time recovery; empty means latest.
	// +kubebuilder:default:=""
	RecoveryTime string `json:"recoveryTime,omitempty"`
}

type Database struct {
	// Roles assigned to users.
	Roles DatabaseRoles `json:"roles,omitempty"`
}

type DatabaseRoles struct {
	// List of users with admin privileges (readWrite + dbAdmin).
	Admin []string `json:"admin,omitempty"`
	// List of users with read-only privileges.
	Readonly []string `json:"readonly,omitempty"`
}

type Resources struct {
	// CPU available to each replica.
	Cpu resource.Quantity `json:"cpu,omitempty"`
	// Memory (RAM) available to each replica.
	Memory resource.Quantity `json:"memory,omitempty"`
}

type Shard struct {
	// Shard name.
	Name string `json:"name"`
	// Number of replicas in this shard.
	Replicas int `json:"replicas"`
	// PVC size for this shard.
	Size resource.Quantity `json:"size"`
}

type ShardingConfig struct {
	// PVC size for config servers.
	// +kubebuilder:default:="3Gi"
	ConfigServerSize resource.Quantity `json:"configServerSize"`
	// Number of config server replicas.
	// +kubebuilder:default:=3
	ConfigServers int `json:"configServers"`
	// Number of mongos router replicas.
	// +kubebuilder:default:=2
	Mongos int `json:"mongos"`
	// List of shard configurations.
	// +kubebuilder:default:={{"name":"rs0","replicas":3,"size":"10Gi"}}
	Shards []Shard `json:"shards,omitempty"`
}

type User struct {
	// Password for the user (auto-generated if omitted).
	Password string `json:"password,omitempty"`
}

// +kubebuilder:validation:Enum="t1.nano";"t1.micro";"t1.small";"t1.medium";"t1.large";"t1.xlarge";"t1.2xlarge";"t1.4xlarge";"c1.nano";"c1.micro";"c1.small";"c1.medium";"c1.large";"c1.xlarge";"c1.2xlarge";"c1.4xlarge";"s1.nano";"s1.micro";"s1.small";"s1.medium";"s1.large";"s1.xlarge";"s1.2xlarge";"s1.4xlarge";"u1.nano";"u1.micro";"u1.small";"u1.medium";"u1.large";"u1.xlarge";"u1.2xlarge";"u1.4xlarge";"m1.nano";"m1.micro";"m1.small";"m1.medium";"m1.large";"m1.xlarge";"m1.2xlarge";"m1.4xlarge";"nano";"micro";"small";"medium";"large";"xlarge";"2xlarge"
type ResourcesPreset string

// +kubebuilder:validation:Enum="v8";"v7";"v6"
type Version string
