// Code generated by values-gen. DO NOT EDIT.
// +kubebuilder:object:generate=true
// +groupName=apps.cozystack.io
// +versionName=v1alpha1
package tcpbalancer

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +kubebuilder:object:root=true
type Config struct {
	v1.TypeMeta   `json:",inline"`
	v1.ObjectMeta `json:"metadata,omitempty"`
	Spec          ConfigSpec `json:"spec,omitempty"`
}

type ConfigSpec struct {
	// Number of HAProxy replicas.
	// +kubebuilder:default:=2
	Replicas int `json:"replicas"`
	// Explicit CPU and memory configuration for each TCP Balancer replica. When omitted, the preset defined in `resourcesPreset` is applied.
	// +kubebuilder:default:={}
	Resources Resources `json:"resources,omitempty"`
	// Default sizing preset used when `resources` is omitted.
	// +kubebuilder:default:="t1.nano"
	ResourcesPreset ResourcesPreset `json:"resourcesPreset"`
	// Enable external access from outside the cluster.
	// +kubebuilder:default:=false
	External bool `json:"external"`
	// HTTP and HTTPS configuration.
	// +kubebuilder:default:={}
	HttpAndHttps HttpAndHttps `json:"httpAndHttps"`
	// Secure HTTP and HTTPS by whitelisting client networks. Requires a non-empty `whitelist` (default: false).
	// +kubebuilder:default:=false
	WhitelistHTTP bool `json:"whitelistHTTP"`
	// List of allowed client networks.
	// +kubebuilder:default:={}
	Whitelist []string `json:"whitelist,omitempty"`
}

type HttpAndHttps struct {
	// Endpoint addresses list.
	// +kubebuilder:default:={}
	Endpoints []string `json:"endpoints,omitempty"`
	// Mode for balancer.
	// +kubebuilder:default:="tcp"
	Mode Mode `json:"mode"`
	// Target ports configuration.
	// +kubebuilder:default:={}
	TargetPorts TargetPorts `json:"targetPorts"`
}

type Resources struct {
	// CPU available to each replica.
	Cpu resource.Quantity `json:"cpu,omitempty"`
	// Memory (RAM) available to each replica.
	Memory resource.Quantity `json:"memory,omitempty"`
}

type TargetPorts struct {
	// HTTP port number.
	// +kubebuilder:default:=80
	Http int `json:"http"`
	// HTTPS port number.
	// +kubebuilder:default:=443
	Https int `json:"https"`
}

// +kubebuilder:validation:Enum="tcp";"tcp-with-proxy"
type Mode string

// +kubebuilder:validation:Enum="t1.nano";"t1.micro";"t1.small";"t1.medium";"t1.large";"t1.xlarge";"t1.2xlarge";"t1.4xlarge";"c1.nano";"c1.micro";"c1.small";"c1.medium";"c1.large";"c1.xlarge";"c1.2xlarge";"c1.4xlarge";"s1.nano";"s1.micro";"s1.small";"s1.medium";"s1.large";"s1.xlarge";"s1.2xlarge";"s1.4xlarge";"u1.nano";"u1.micro";"u1.small";"u1.medium";"u1.large";"u1.xlarge";"u1.2xlarge";"u1.4xlarge";"m1.nano";"m1.micro";"m1.small";"m1.medium";"m1.large";"m1.xlarge";"m1.2xlarge";"m1.4xlarge";"nano";"micro";"small";"medium";"large";"xlarge";"2xlarge"
type ResourcesPreset string
