// Code generated by values-gen. DO NOT EDIT.
// +kubebuilder:object:generate=true
// +groupName=apps.cozystack.io
// +versionName=v1alpha1
package tenant

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +kubebuilder:object:root=true
type Config struct {
	v1.TypeMeta   `json:",inline"`
	v1.ObjectMeta `json:"metadata,omitempty"`
	Spec          ConfigSpec `json:"spec,omitempty"`
}

type ConfigSpec struct {
	// The hostname used to access tenant services (defaults to using the tenant name as a subdomain for its parent tenant host).
	// +kubebuilder:default:=""
	Host string `json:"host,omitempty"`
	// Deploy own Etcd cluster.
	// +kubebuilder:default:=false
	Etcd bool `json:"etcd"`
	// Deploy own Monitoring Stack.
	// +kubebuilder:default:=false
	Monitoring bool `json:"monitoring"`
	// Deploy own Ingress Controller.
	// +kubebuilder:default:=false
	Ingress bool `json:"ingress"`
	// Deploy own Gateway API Gateway (backed by Cilium Gateway API controller). When unset (the default) or set to `false`, the tenant does not own a Gateway and instead publishes through the nearest ancestor tenant that owns one, regardless of whether `host` is empty or custom (`false` currently behaves the same as unset and does not opt out of that inheritance). Set to `true` to give the tenant its own Gateway with its own LoadBalancer IP and Certificate. A tenant with a custom (non-derived) `host` that needs its apex publicly reachable must set `true` explicitly, because an ancestor's TLS certificate does not cover a custom apex. Note: leave the key absent (do not write `gateway: null`): the chart distinguishes "unset" via missing-key, not via null value, to satisfy the JSON schema generated from this comment.
	Gateway bool `json:"gateway,omitempty"`
	// GatewayClass for this tenant's own Gateway. Empty uses the platform default (`gateway.className`). Only the classes the operator lists in the platform's `gateway.tenantSelectableClasses`, plus that default, may be named here — anything else fails this tenant's own gateway release and reaches no other tenant. Read only when this tenant owns a Gateway; an inheriting tenant uses its ancestor's. Whether a class terminates TLS itself or at its provider's edge is declared once per class on the platform, not here.
	// +kubebuilder:default:=""
	GatewayClass string `json:"gatewayClass,omitempty"`
	// Deploy own SeaweedFS.
	// +kubebuilder:default:=false
	Seaweedfs bool `json:"seaweedfs"`
	// Deploy own ComputePlane — a single-tenant, Cozystack-managed cluster for untrusted-code applications. The tenant receives no admin kubeconfig for it. Automatic routing of catalog applications onto it (placement: ComputePlane) is a planned follow-up and is not available yet; until it lands, external catalogs target the cluster via its computeplane-cluster-admin-kubeconfig Secret. See design-proposals/compute-plane in cozystack/community.
	// +kubebuilder:default:=false
	Computeplane bool `json:"computeplane"`
	// The name of a SchedulingClass CR to apply scheduling constraints for this tenant's workloads.
	// +kubebuilder:default:=""
	SchedulingClass string `json:"schedulingClass,omitempty"`
	// Define resource quotas for the tenant.
	// +kubebuilder:default:={}
	ResourceQuotas map[string]resource.Quantity `json:"resourceQuotas,omitempty"`
}
