// Code generated by values-gen. DO NOT EDIT.
// +kubebuilder:object:generate=true
// +groupName=apps.cozystack.io
// +versionName=v1alpha1
package tenant

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +kubebuilder:object:root=true
type Config struct {
	v1.TypeMeta   `json:",inline"`
	v1.ObjectMeta `json:"metadata,omitempty"`
	Spec          ConfigSpec `json:"spec,omitempty"`
}

type ConfigSpec struct {
	// The hostname used to access tenant services (defaults to using the tenant name as a subdomain for its parent tenant host).
	// +kubebuilder:default:=""
	Host string `json:"host,omitempty"`
	// Deploy own Etcd cluster.
	// +kubebuilder:default:=false
	Etcd bool `json:"etcd"`
	// Deploy own Monitoring Stack.
	// +kubebuilder:default:=false
	Monitoring bool `json:"monitoring"`
	// Deploy own Ingress Controller.
	// +kubebuilder:default:=false
	Ingress bool `json:"ingress"`
	// Deploy own Gateway API Gateway (backed by Cilium Gateway API controller). When unset (the default), the chart auto-enables the Gateway for tenants whose apex is derived from the parent (i.e. `host` is empty), and leaves it off for tenants with a custom non-derived apex. Set to `true` or `false` explicitly to override that auto-behaviour. Note: leave the key absent (do not write `gateway: null`) — the chart distinguishes "unset" via missing-key, not via null value, to satisfy the JSON schema generated from this comment.
	Gateway bool `json:"gateway,omitempty"`
	// Deploy own SeaweedFS.
	// +kubebuilder:default:=false
	Seaweedfs bool `json:"seaweedfs"`
	// Deploy own ComputePlane — a single-tenant, Cozystack-managed cluster for untrusted-code applications. Applications with placement: ComputePlane are routed onto it. The tenant receives no admin kubeconfig for it. See design-proposals/compute-plane in cozystack/community.
	// +kubebuilder:default:=false
	Computeplane bool `json:"computeplane"`
	// The name of a SchedulingClass CR to apply scheduling constraints for this tenant's workloads.
	// +kubebuilder:default:=""
	SchedulingClass string `json:"schedulingClass,omitempty"`
	// Define resource quotas for the tenant.
	// +kubebuilder:default:={}
	ResourceQuotas map[string]resource.Quantity `json:"resourceQuotas,omitempty"`
}
