metallb:
  crds:
    enabled: true
  controller:
    image:
      repository: ghcr.io/cozystack/cozystack/metallb-controller
      tag: v0.15.2@sha256:0e9080234fc8eedab78ad2831fb38df375c383e901a752d72b353c8d13b9605f
  speaker:
    image:
      repository: ghcr.io/cozystack/cozystack/metallb-speaker
      tag: v0.15.2@sha256:e14d4c328c3ab91a6eadfeea90da96388503492d165e7e8582f291b1872e53b2
