cilium:
  kubeProxyReplacement: true
  hubble:
    enabled: false
  externalIPs:
    enabled: true
  nodePort:
    enabled: true
  loadBalancer:
    algorithm: maglev
  ipam:
    mode: "kubernetes"
  image:
    repository: ghcr.io/aenix-io/cozystack/cilium
    tag: latest
    digest: "sha256:a731981fef38429551dabdbc347b0f9af66a9f935bcc861117d63bc6681b3ec0"
  envoy:
    enabled: false
