cilium:
  kubeProxyReplacement: true
  hubble:
    enabled: false
  externalIPs:
    enabled: true
  nodePort:
    enabled: true
  loadBalancer:
    algorithm: maglev
  ipam:
    mode: "kubernetes"
  image:
    repository: ghcr.io/aenix-io/cozystack/cilium
    tag: 1.16.7
    digest: "sha256:d2d6f5675aa30c18c4d9c08c27448173416cfb4a84080d5b9765fa1bdc9b4c70"
  envoy:
    enabled: false
