{{- $controllerReplicas := 3 }}
{{- if le (int .Values.kafka.replicas) 1 }}
  {{- $controllerReplicas = 1 }}
{{- end }}
---
apiVersion: cozystack.io/v1alpha1
kind: WorkloadMonitor
metadata:
  name: {{ $.Release.Name }}
  labels:
    workloads.cozystack.io/resource-preset: {{ .Values.kafka.resourcesPreset | quote }}
spec:
  replicas: {{ .Values.kafka.replicas }}
  minReplicas: 1
  kind: kafka
  type: kafka-broker
  selector:
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/name: kafka
    strimzi.io/pool-name: {{ $.Release.Name }}-broker
  version: {{ $.Chart.Version }}
---
apiVersion: cozystack.io/v1alpha1
kind: WorkloadMonitor
metadata:
  name: {{ $.Release.Name }}-controller
  labels:
    workloads.cozystack.io/resource-preset: {{ .Values.kafka.resourcesPreset | quote }}
spec:
  replicas: {{ $controllerReplicas }}
  minReplicas: 1
  kind: kafka
  type: kafka-controller
  selector:
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/name: kafka
    strimzi.io/pool-name: {{ $.Release.Name }}-controller
  version: {{ $.Chart.Version }}
