{{- if .Values.resourceQuotas }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant-quota
  namespace: {{ include "tenant.name" . }}
spec:
  hard:
    {{- include "cozy-lib.resources.flatten" (list .Values.resourceQuotas $) | nindent 6 }}
{{- end }}
