{{- if .Values.resourceQuotas }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant-quota
  namespace: {{ include "tenant.name" . }}
spec:
  hard:
    {{- include "cozy-lib.resources.flatten" (list .Values.resourceQuotas $) | nindent 6 }}
---
apiVersion: v1
kind: LimitRange
metadata:
  name: tenant-range-limits
  namespace: {{ include "tenant.name" . }}
spec:
  limits:
    - default:
        cpu: "250m"
        memory: "128Mi"
        ephemeral-storage: "2Gi"
      defaultRequest:
        cpu: "25m"
        memory: "128Mi"
        ephemeral-storage: "50Mi"
      type: Container
{{- end }}
