apiVersion: v1
kind: ConfigMap
metadata:
  name: v1.0.3-ipam-in-cluster
  labels:
    ipamprovider-provider: in-cluster
  annotations:
    provider.cluster.x-k8s.io/compressed: "true"
binaryData:
  components: {{ .Files.Get "files/components.gz" | b64enc | quote }}
data:
  metadata: {{ .Files.Get "files/metadata.yaml" | quote }}
