{{- range .Values.metricsStorages }}
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: {{ .name }}
spec:
  replicationFactor: 2
  retentionPeriod: {{ .retentionPeriod | quote }}
  vminsert:
    replicaCount: 2
    resources:
      {{- if empty .vminsert.resources }}
      limits:
        memory: 1000Mi
      requests:
        cpu: 100m
        memory: 500Mi
      {{- else }}
      {{- toYaml .vminsert.resources | nindent 6 }}
      {{- end }}
  vmselect:
    replicaCount: 2
    resources:
      {{- if empty .vmselect.resources }}
      limits:
        memory: 1000Mi
      requests:
        cpu: 100m
        memory: 500Mi
      {{- else }}
      {{- toYaml .vmselect.resources | nindent 6 }}
      {{- end }}
    extraArgs:
      search.maxUniqueTimeseries: "600000"
      vmalert.proxyURL: http://vmalert-{{ .name }}.{{ $.Release.Namespace }}.svc:8080
      dedup.minScrapeInterval: {{ .deduplicationInterval | quote}}
    cacheMountPath: /select-cache
    storage:
      volumeClaimTemplate:
        spec:
          {{- with .storageClassName }}
          storageClassName: {{ . }}
          {{- end }}
          resources:
            requests:
              storage: 2Gi
  vmstorage:
    replicaCount: 2
    resources:
      {{- if empty .vmstorage.resources }}
      limits:
        memory: 2048Mi
      requests:
        cpu: 100m
        memory: 500Mi
      {{- else }}
      {{- toYaml .vmstorage.resources | nindent 6 }}
      {{- end }}
    storage:
      volumeClaimTemplate:
        spec:
          {{- with .storageClassName }}
          storageClassName: {{ . }}
          {{- end }}
          resources:
            requests:
              storage: {{ .storage }}
    storageDataPath: /vm-data
---
apiVersion: cozystack.io/v1alpha1
kind: WorkloadMonitor
metadata:
  name: {{ .name }}-vmstorage
spec:
  replicas: 2
  minReplicas: 1
  kind: monitoring
  type: vmstorage
  selector:
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/instance: {{ .name }}
    app.kubernetes.io/name: vmstorage
  version: {{ $.Chart.Version }}
---
apiVersion: cozystack.io/v1alpha1
kind: WorkloadMonitor
metadata:
  name: {{ .name }}-vmselect
spec:
  replicas: 2
  minReplicas: 1
  kind: monitoring
  type: vmselect
  selector:
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/instance: {{ .name }}
    app.kubernetes.io/name: vmselect
  version: {{ $.Chart.Version }}
---
apiVersion: cozystack.io/v1alpha1
kind: WorkloadMonitor
metadata:
  name: {{ .name }}-vminsert
spec:
  replicas: 2
  minReplicas: 1
  kind: monitoring
  type: vminsert
  selector:
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/instance: {{ .name }}
    app.kubernetes.io/name: vminsert
  version: {{ $.Chart.Version }}
{{- end }}
