---
apiVersion: cozystack.io/v1alpha1
kind: WorkloadMonitor
metadata:
  name: {{ $.Release.Name }}-haproxy
spec:
  replicas: {{ .Values.haproxy.replicas }}
  minReplicas: 1
  kind: http-cache
  type: http-cache
  selector:
    app: {{ $.Release.Name }}-haproxy
  version: {{ $.Chart.Version }}
---
apiVersion: cozystack.io/v1alpha1
kind: WorkloadMonitor
metadata:
  name: {{ $.Release.Name }}-nginx
spec:
  replicas: {{ .Values.nginx.replicas }}
  minReplicas: 1
  kind: http-cache
  type: http-cache
  selector:
    app: {{ $.Release.Name }}-nginx-cache
  version: {{ $.Chart.Version }}
---
apiVersion: cozystack.io/v1alpha1
kind: WorkloadMonitor
metadata:
  name: {{ $.Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  minReplicas: 1
  kind: http-cache
  type: http-cache
  selector:
    app.kubernetes.io/instance: {{ $.Release.Name }}
  version: {{ $.Chart.Version }}
