vpaForVPA: true

vertical-pod-autoscaler:
  crds:
    enabled: false

    image:
      registry: docker.io
      repository: alpine/k8s
      tag: 1.33.4

  updater:
    resources:
      limits:
        memory: 110Mi
      requests:
        cpu: 200m
        memory: 110Mi

  recommender:
    extraArgs:
      container-name-label: container
      container-namespace-label: namespace
      container-pod-name-label: pod
      storage: prometheus
      memory-saver: true
      pod-label-prefix: label_
      metric-for-pod-labels: kube_pod_labels{job="kube-state-metrics"}[8d]
      pod-name-label: pod
      pod-namespace-label: namespace
      prometheus-address: http://vmselect-shortterm.tenant-root.svc.cozy.local:8481/select/0/prometheus/
      prometheus-cadvisor-job-name: cadvisor

  admissionController:
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 50Mi
