---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: CoreProvider
metadata:
  name: cluster-api
spec:
  # https://github.com/kubernetes-sigs/cluster-api
  version: v1.10.1-core
  fetchConfig:
    selector:
      matchLabels:
        core-components: cozy
