{{- if .Values.addons.gpuOperator.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ .Release.Name }}-gpu-operator
  labels:
    cozystack.io/repository: system
    cozystack.io/target-cluster-name: {{ .Release.Name }}
spec:
  interval: 5m
  releaseName: gpu-operator
  chart:
    spec:
      chart: cozy-gpu-operator
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
  kubeConfig:
    secretRef:
      name: {{ .Release.Name }}-admin-kubeconfig
      key: super-admin.svc
  targetNamespace: cozy-gpu-operator
  storageNamespace: cozy-gpu-operator
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  {{- if .Values.addons.gpuOperator.valuesOverride }}
  valuesFrom:
  - kind: Secret
    name: {{ .Release.Name }}-gpu-operator-values-override
    valuesKey: values
  {{- end }}

  dependsOn:
  {{- if lookup "helm.toolkit.fluxcd.io/v2" "HelmRelease" .Release.Namespace .Release.Name }}
  - name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
  {{- end }}
  - name: {{ .Release.Name }}-cilium
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- if .Values.addons.gpuOperator.valuesOverride }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-gpu-operator-values-override
stringData:
  values: |
    {{- toYaml .Values.addons.gpuOperator.valuesOverride | nindent 4 }}
{{- end }}
