---
apiVersion: cozystack.io/v1alpha1
kind: PackageSource
metadata:
  name: cozystack.kubernetes-worker-image
spec:
  sourceRef:
    kind: OCIRepository
    name: cozystack-packages
    namespace: cozy-system
    path: /
  variants:
    - name: default
      dependsOn:
        - cozystack.networking
        - cozystack.kubevirt-cdi
      components:
        - name: kubernetes-worker-image
          path: system/kubernetes-worker-image
          install:
            namespace: cozy-system
            releaseName: kubernetes-worker-image
