---
apiVersion: cozystack.io/v1alpha1
kind: PackageSource
metadata:
  name: cozystack.local-storage
spec:
  sourceRef:
    kind: OCIRepository
    name: cozystack-packages
    namespace: cozy-system
    path: /
  variants:
  - name: default
    dependsOn:
    - cozystack.networking
    components:
    - name: local-storage
      path: system/local-storage
      install:
        privileged: true
        namespace: cozy-local-storage
        releaseName: local-storage
