---
apiVersion: cozystack.io/v1alpha1
kind: PackageSource
metadata:
  name: cozystack.opensearch-operator
spec:
  sourceRef:
    kind: OCIRepository
    name: cozystack-packages
    namespace: cozy-system
    path: /
  variants:
  - name: default
    dependsOn:
    - cozystack.networking
    - cozystack.prometheus-operator-crds
    components:
    - name: opensearch-operator
      path: system/opensearch-operator
      install:
        privileged: true
        namespace: cozy-opensearch-operator
        releaseName: opensearch-operator
