// Code generated by values-gen. DO NOT EDIT.
// +kubebuilder:object:generate=true
// +groupName=apps.cozystack.io
// +versionName=v1alpha1
package clickhouse

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +kubebuilder:object:root=true
type Config struct {
	v1.TypeMeta   `json:",inline"`
	v1.ObjectMeta `json:"metadata,omitempty"`
	Spec          ConfigSpec `json:"spec,omitempty"`
}

type ConfigSpec struct {
	// Number of ClickHouse replicas.
	// +kubebuilder:default:=2
	Replicas int `json:"replicas"`
	// Number of ClickHouse shards.
	// +kubebuilder:default:=1
	Shards int `json:"shards"`
	// Explicit CPU and memory configuration for each ClickHouse replica. When omitted, the preset defined in `resourcesPreset` is applied.
	// +kubebuilder:default:={}
	Resources Resources `json:"resources,omitempty"`
	// Default sizing preset used when `resources` is omitted.
	// +kubebuilder:default:="t1.small"
	ResourcesPreset ResourcesPreset `json:"resourcesPreset"`
	// Persistent Volume Claim size available for application data.
	// +kubebuilder:default:="10Gi"
	Size resource.Quantity `json:"size"`
	// StorageClass used to store the data.
	// +kubebuilder:default:=""
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="storageClass is immutable"
	StorageClass string `json:"storageClass"`
	// Size of Persistent Volume for logs.
	// +kubebuilder:default:="2Gi"
	LogStorageSize resource.Quantity `json:"logStorageSize"`
	// TTL (expiration time) for `query_log` and `query_thread_log`.
	// +kubebuilder:default:=15
	LogTTL int `json:"logTTL"`
	// Users configuration map.
	// +kubebuilder:default:={}
	Users map[string]User `json:"users,omitempty"`
	// Backup configuration.
	// +kubebuilder:default:={}
	Backup Backup `json:"backup"`
	// ClickHouse Keeper configuration.
	// +kubebuilder:default:={}
	ClickhouseKeeper ClickHouseKeeper `json:"clickhouseKeeper"`
}

type Backup struct {
	// Legacy. Restic retention policy passed to the legacy CronJob (`restic forget …`). Unused by the Altinity strategy.
	// +kubebuilder:default:="--keep-last=3 --keep-daily=3 --keep-within-weekly=1m"
	CleanupStrategy string `json:"cleanupStrategy,omitempty"`
	// Enable backup integration. Materialises the chart-emitted `<release>-backup-s3` Secret consumed by the Altinity backup strategy and, when `schedule` is non-empty, also renders the legacy chart-managed CronJob.
	// +kubebuilder:default:=false
	Enabled bool `json:"enabled"`
	// DEPRECATED. S3 endpoint URL for the legacy chart-emitted sidecar.
	// +kubebuilder:default:=""
	Endpoint string `json:"endpoint,omitempty"`
	// CA bundle the sidecar trusts when the S3 endpoint's certificate is signed by a private CA (e.g. Cozystack's in-cluster SeaweedFS). Applies to both the per-tenant and the `useSystemBucket` flow, and to the `clickhouse-backup` sidecar only — the legacy `schedule` CronJob writes to S3 through restic and does not consume it, so a private-CA endpoint combined with `schedule` still fails TLS. Use the BackupClass flow for such an endpoint.
	// +kubebuilder:default:={}
	EndpointCA EndpointCA `json:"endpointCA,omitempty"`
	// Legacy. Password for Restic backup encryption used by the legacy CronJob. Unused by the Altinity strategy.
	// +kubebuilder:default:="<password>"
	ResticPassword string `json:"resticPassword,omitempty"`
	// DEPRECATED. Tenants no longer supply S3 keys; the platform-managed Bucket Secret is the source of truth. Optional now so `useSystemBucket: true` tenants can omit it.
	// +kubebuilder:default:="<your-access-key>"
	S3AccessKey string `json:"s3AccessKey,omitempty"`
	// DEPRECATED. Optional; see `s3Region`.
	// +kubebuilder:default:="s3.example.org/clickhouse-backups"
	S3Bucket string `json:"s3Bucket,omitempty"`
	// DEPRECATED. Pre-existing Secret reference for the legacy chart-emitted sidecar. The platform flow projects `cozy-backups-creds` instead.
	// +kubebuilder:default:={}
	S3CredentialsSecret S3CredentialsSecret `json:"s3CredentialsSecret,omitempty"`
	// DEPRECATED. Object-key prefix inside the legacy `s3Bucket`; the new platform flow scopes by namespace automatically.
	// +kubebuilder:default:=""
	S3PathOverride string `json:"s3PathOverride,omitempty"`
	// DEPRECATED. Per-tenant S3 configuration is being phased out in favour of the platform-managed `cozy-default` BackupClass. Optional now so tenants on `useSystemBucket: true` can omit it.
	// +kubebuilder:default:="us-east-1"
	S3Region string `json:"s3Region,omitempty"`
	// DEPRECATED. Optional; see `s3AccessKey`.
	// +kubebuilder:default:="<your-secret-key>"
	S3SecretKey string `json:"s3SecretKey,omitempty"`
	// Legacy. Cron schedule for the chart-emitted CronJob that runs the dump+restic backup. Empty (default) skips the legacy CronJob; recommended when a `BackupClass` + `Plan` from `backups.cozystack.io` already drives backup orchestration via the Altinity strategy.
	// +kubebuilder:default:=""
	Schedule string `json:"schedule,omitempty"`
	// Opt-in: when true, the chart-emitted `<release>-backup-s3` Secret is skipped and the `clickhouse-backup` sidecar reads bucket coordinates + S3 credentials from the platform-projected `cozy-backups-creds` Secret. `S3_PATH` is set to `<namespace>/<release>` for cross-tenant isolation. Use together with the platform `cozy-default` BackupClass — tenants do not need to fill any `s3*` field below.
	// +kubebuilder:default:=false
	UseSystemBucket bool `json:"useSystemBucket,omitempty"`
}

type ClickHouseKeeper struct {
	// Deploy ClickHouse Keeper for cluster coordination.
	// +kubebuilder:default:=true
	Enabled bool `json:"enabled,omitempty"`
	// Number of Keeper replicas.
	// +kubebuilder:default:=3
	Replicas int `json:"replicas,omitempty"`
	// Default sizing preset.
	// +kubebuilder:default:="t1.micro"
	ResourcesPreset ResourcesPreset `json:"resourcesPreset,omitempty"`
	// Persistent Volume Claim size available for application data.
	// +kubebuilder:default:="1Gi"
	Size resource.Quantity `json:"size,omitempty"`
}

type EndpointCA struct {
	// Key inside the Secret holding the PEM CA bundle. Defaults to `ca.crt`.
	// +kubebuilder:default:="ca.crt"
	Key string `json:"key,omitempty"`
	// Name of the Secret in the application namespace. Empty (default) mounts nothing and leaves the sidecar on the system trust store only.
	// +kubebuilder:default:=""
	Name string `json:"name,omitempty"`
}

type Resources struct {
	// CPU available to each replica.
	Cpu resource.Quantity `json:"cpu,omitempty"`
	// Memory (RAM) available to each replica.
	Memory resource.Quantity `json:"memory,omitempty"`
}

type S3CredentialsSecret struct {
	// Key in the Secret holding the access key ID. Defaults to `accessKey`.
	// +kubebuilder:default:=""
	AccessKeyIDKey string `json:"accessKeyIDKey,omitempty"`
	// Key in the Secret holding the bucket name. Defaults to `bucketName`.
	// +kubebuilder:default:=""
	BucketKey string `json:"bucketKey,omitempty"`
	// Key in the Secret holding the S3 endpoint URL. Defaults to `endpoint`.
	// +kubebuilder:default:=""
	EndpointKey string `json:"endpointKey,omitempty"`
	// Name of the Secret in the application namespace. Empty means the chart materialises `<release>-backup-s3` from the legacy `s3*` fields.
	// +kubebuilder:default:=""
	Name string `json:"name,omitempty"`
	// Key in the Secret holding the S3 region. Defaults to `region`.
	// +kubebuilder:default:=""
	RegionKey string `json:"regionKey,omitempty"`
	// Key in the Secret holding the secret access key. Defaults to `secretKey`.
	// +kubebuilder:default:=""
	SecretAccessKeyKey string `json:"secretAccessKeyKey,omitempty"`
}

type User struct {
	// Password for the user.
	Password string `json:"password,omitempty"`
	// User is readonly (default: false).
	Readonly bool `json:"readonly,omitempty"`
}

// +kubebuilder:validation:Enum="t1.nano";"t1.micro";"t1.small";"t1.medium";"t1.large";"t1.xlarge";"t1.2xlarge";"t1.4xlarge";"c1.nano";"c1.micro";"c1.small";"c1.medium";"c1.large";"c1.xlarge";"c1.2xlarge";"c1.4xlarge";"s1.nano";"s1.micro";"s1.small";"s1.medium";"s1.large";"s1.xlarge";"s1.2xlarge";"s1.4xlarge";"u1.nano";"u1.micro";"u1.small";"u1.medium";"u1.large";"u1.xlarge";"u1.2xlarge";"u1.4xlarge";"m1.nano";"m1.micro";"m1.small";"m1.medium";"m1.large";"m1.xlarge";"m1.2xlarge";"m1.4xlarge";"nano";"micro";"small";"medium";"large";"xlarge";"2xlarge"
type ResourcesPreset string
