apiVersion: v1
kind: Service
metadata:
  name: kube-ovn-plunger
  labels:
    app.kubernetes.io/name: kube-ovn-plunger
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: kube-ovn-plunger
    app.kubernetes.io/instance: {{ .Release.Name }}
