apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: kube-ovn-plunger
  labels:
    app.kubernetes.io/name: kube-ovn-plunger
    app.kubernetes.io/instance: {{ .Release.Name }}
