---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: seaweedfs-db
spec:
  instances: 2
  storage:
    size: 10Gi

  monitoring:
    enablePodMonitor: true
  resources:
    limits:
      cpu: "1"
      memory: 2048Mi
    requests:
      cpu: 100m
      memory: 512Mi
  inheritedMetadata:
    labels:
      policy.cozystack.io/allow-to-apiserver: "true"
