// Code generated by values-gen. DO NOT EDIT.
// +kubebuilder:object:generate=true
// +groupName=apps.cozystack.io
// +versionName=v1alpha1
package mariadb

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +kubebuilder:object:root=true
type Config struct {
	v1.TypeMeta   `json:",inline"`
	v1.ObjectMeta `json:"metadata,omitempty"`
	Spec          ConfigSpec `json:"spec,omitempty"`
}

type ConfigSpec struct {
	// Number of MariaDB replicas.
	// +kubebuilder:default:=2
	Replicas int `json:"replicas"`
	// Explicit CPU and memory configuration for each MariaDB replica. When omitted, the preset defined in `resourcesPreset` is applied.
	// +kubebuilder:default:={}
	Resources Resources `json:"resources,omitempty"`
	// Default sizing preset used when `resources` is omitted.
	// +kubebuilder:default:="t1.nano"
	ResourcesPreset ResourcesPreset `json:"resourcesPreset"`
	// Persistent Volume Claim size available for application data.
	// +kubebuilder:default:="10Gi"
	Size resource.Quantity `json:"size"`
	// StorageClass used to store the data.
	// +kubebuilder:default:=""
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="storageClass is immutable"
	StorageClass string `json:"storageClass"`
	// Enable external access from outside the cluster.
	// +kubebuilder:default:=false
	External bool `json:"external"`
	// TLS configuration. Selects who issues the certificates and whether plaintext is refused; TLS itself is always served.
	// +kubebuilder:default:={}
	Tls TLS `json:"tls,omitempty"`
	// MariaDB major.minor version to deploy
	// +kubebuilder:default:="v11.8"
	Version Version `json:"version"`
	// Users configuration map. Passwords (including the `root` account) are always auto-generated and stored in the `<release>-credentials` Secret; they cannot be set from values — read a user's password from that Secret. A `password` left over in values from before the field was removed is ignored by the render and draws an admission warning, but it is not inert on an upgraded release: the chart preserves whatever password is already in the Secret, which on the first upgrade is the value that was set before removal, so that value stays the live credential until it is rotated (dedicated rotation is tracked in cozystack/community#72). The live password lives only in the Secret.
	// +kubebuilder:default:={}
	Users map[string]User `json:"users,omitempty"`
	// Databases configuration map.
	// +kubebuilder:default:={}
	Databases map[string]Database `json:"databases,omitempty"`
	// DEPRECATED: Backup configuration. Prefer the BackupClass / Plan flow under examples/backups/mariadb/.
	// +kubebuilder:default:={}
	Backup Backup `json:"backup"`
}

type Backup struct {
	// DEPRECATED: Retention strategy for cleaning up old backups.
	// +kubebuilder:default:="--keep-last=3 --keep-daily=3 --keep-within-weekly=1m"
	CleanupStrategy string `json:"cleanupStrategy"`
	// DEPRECATED: Enable regular backups (default: false).
	// +kubebuilder:default:=false
	Enabled bool `json:"enabled"`
	// DEPRECATED: Password for Restic backup encryption.
	// +kubebuilder:default:="<password>"
	ResticPassword string `json:"resticPassword"`
	// DEPRECATED: Access key for S3 authentication.
	// +kubebuilder:default:="<your-access-key>"
	S3AccessKey string `json:"s3AccessKey"`
	// DEPRECATED: S3 bucket used for storing backups.
	// +kubebuilder:default:="s3.example.org/mariadb-backups"
	S3Bucket string `json:"s3Bucket"`
	// DEPRECATED: AWS S3 region where backups are stored.
	// +kubebuilder:default:="us-east-1"
	S3Region string `json:"s3Region"`
	// DEPRECATED: Secret key for S3 authentication.
	// +kubebuilder:default:="<your-secret-key>"
	S3SecretKey string `json:"s3SecretKey"`
	// DEPRECATED: Cron schedule for automated backups.
	// +kubebuilder:default:="0 2 * * *"
	Schedule string `json:"schedule"`
}

type Database struct {
	// Roles assigned to users.
	Roles DatabaseRoles `json:"roles,omitempty"`
}

type DatabaseRoles struct {
	// List of users with admin privileges.
	Admin []string `json:"admin,omitempty"`
	// List of users with read-only privileges.
	Readonly []string `json:"readonly,omitempty"`
}

type Resources struct {
	// CPU available to each replica.
	Cpu resource.Quantity `json:"cpu,omitempty"`
	// Memory (RAM) available to each replica.
	Memory resource.Quantity `json:"memory,omitempty"`
}

type TLS struct {
	// Who issues the server certificate: `operator` uses the CA mariadb-operator manages itself, `cert-manager` gives the instance its own CA and is what covers the external hostname. Named for the issuer because TLS is served under both, unlike the similarly-spelled `tls.enabled` in some other charts, which does switch TLS on and off.
	// +kubebuilder:default:="operator"
	Issuer TLSIssuer `json:"issuer,omitempty"`
	// Refuse plaintext connections (sets MariaDB require_secure_transport=ON). Applies under either issuer. Opt-in: turn it on once every client connects over TLS, since it disconnects those that do not.
	Required *bool `json:"required,omitempty"`
}

type User struct {
	// Maximum number of connections.
	MaxUserConnections int `json:"maxUserConnections"`
}

// +kubebuilder:validation:Enum="t1.nano";"t1.micro";"t1.small";"t1.medium";"t1.large";"t1.xlarge";"t1.2xlarge";"t1.4xlarge";"c1.nano";"c1.micro";"c1.small";"c1.medium";"c1.large";"c1.xlarge";"c1.2xlarge";"c1.4xlarge";"s1.nano";"s1.micro";"s1.small";"s1.medium";"s1.large";"s1.xlarge";"s1.2xlarge";"s1.4xlarge";"u1.nano";"u1.micro";"u1.small";"u1.medium";"u1.large";"u1.xlarge";"u1.2xlarge";"u1.4xlarge";"m1.nano";"m1.micro";"m1.small";"m1.medium";"m1.large";"m1.xlarge";"m1.2xlarge";"m1.4xlarge";"nano";"micro";"small";"medium";"large";"xlarge";"2xlarge"
type ResourcesPreset string

// +kubebuilder:validation:Enum="operator";"cert-manager"
type TLSIssuer string

// +kubebuilder:validation:Enum="v11.8";"v11.4";"v10.11";"v10.6"
type Version string
