apiVersion: v1
kind: ConfigMap
metadata:
  name: cozystack-api
  namespace: cozy-system
data:
  config.yaml: |
    resources:
    - application:
        kind: Bucket
        singular: bucket
        plural: buckets
        openAPISchema: {{ .Files.Get "openapi-schemas/bucket.json" | fromJson | toJson | quote }}
      release:
        prefix: bucket-
        labels:
          cozystack.io/ui: "true"
        chart:
          name: bucket
          sourceRef:
            kind: HelmRepository
            name: cozystack-apps
            namespace: cozy-public
    - application:
        kind: ClickHouse
        singular: clickhouse
        plural: clickhouses
        openAPISchema: {{ .Files.Get "openapi-schemas/clickhouse.json" | fromJson | toJson | quote }}
      release:
        prefix: clickhouse-
        labels:
          cozystack.io/ui: "true"
        chart:
          name: clickhouse
          sourceRef:
            kind: HelmRepository
            name: cozystack-apps
            namespace: cozy-public
    - application:
        kind: HTTPCache
        singular: httpcache
        plural: httpcaches
        openAPISchema: {{ .Files.Get "openapi-schemas/http-cache.json" | fromJson | toJson | quote }}
      release:
        prefix: http-cache-
        labels:
          cozystack.io/ui: "true"
        chart:
          name: http-cache
          sourceRef:
            kind: HelmRepository
            name: cozystack-apps
            namespace: cozy-public
    - application:
        kind: NATS
        singular: nats
        plural: natses
        openAPISchema: {{ .Files.Get "openapi-schemas/nats.json" | fromJson | toJson | quote }}
      release:
        prefix: nats-
        labels:
          cozystack.io/ui: "true"
        chart:
          name: nats
          sourceRef:
            kind: HelmRepository
            name: cozystack-apps
            namespace: cozy-public
    - application:
        kind: TCPBalancer
        singular: tcpbalancer
        plural: tcpbalancers
        openAPISchema: {{ .Files.Get "openapi-schemas/tcp-balancer.json" | fromJson | toJson | quote }}
      release:
        prefix: tcp-balancer-
        labels:
          cozystack.io/ui: "true"
        chart:
          name: tcp-balancer
          sourceRef:
            kind: HelmRepository
            name: cozystack-apps
            namespace: cozy-public
    - application:
        kind: VirtualMachine
        singular: virtualmachine
        plural: virtualmachines
        openAPISchema: {{ .Files.Get "openapi-schemas/virtual-machine.json" | fromJson | toJson | quote }}
      release:
        prefix: virtual-machine-
        labels:
          cozystack.io/ui: "true"
        chart:
          name: virtual-machine
          sourceRef:
            kind: HelmRepository
            name: cozystack-apps
            namespace: cozy-public
    - application:
        kind: VPN
        singular: vpn
        plural: vpns
        openAPISchema: {{ .Files.Get "openapi-schemas/vpn.json" | fromJson | toJson | quote }}
      release:
        prefix: vpn-
        labels:
          cozystack.io/ui: "true"
        chart:
          name: vpn
          sourceRef:
            kind: HelmRepository
            name: cozystack-apps
            namespace: cozy-public
    - application:
        kind: MySQL
        singular: mysql
        plural: mysqls
        openAPISchema: {{ .Files.Get "openapi-schemas/mysql.json" | fromJson | toJson | quote }}
      release:
        prefix: mysql-
        labels:
          cozystack.io/ui: "true"
        chart:
          name: mysql
          sourceRef:
            kind: HelmRepository
            name: cozystack-apps
            namespace: cozy-public
    - application:
        kind: Tenant
        singular: tenant
        plural: tenants
        openAPISchema: {{ .Files.Get "openapi-schemas/tenant.json" | fromJson | toJson | quote }}
      release:
        prefix: tenant-
        labels:
          cozystack.io/ui: "true"
        chart:
          name: tenant
          sourceRef:
            kind: HelmRepository
            name: cozystack-apps
            namespace: cozy-public
    - application:
        kind: Kubernetes
        singular: kubernetes
        plural: kuberneteses
        openAPISchema: {{ .Files.Get "openapi-schemas/kubernetes.json" | fromJson | toJson | quote }}
      release:
        prefix: kubernetes-
        labels:
          cozystack.io/ui: "true"
        chart:
          name: kubernetes
          sourceRef:
            kind: HelmRepository
            name: cozystack-apps
            namespace: cozy-public
    - application:
        kind: Redis
        singular: redis
        plural: redises
        openAPISchema: {{ .Files.Get "openapi-schemas/redis.json" | fromJson | toJson | quote }}
      release:
        prefix: redis-
        labels:
          cozystack.io/ui: "true"
        chart:
          name: redis
          sourceRef:
            kind: HelmRepository
            name: cozystack-apps
            namespace: cozy-public
    - application:
        kind: RabbitMQ
        singular: rabbitmq
        plural: rabbitmqs
        openAPISchema: {{ .Files.Get "openapi-schemas/rabbitmq.json" | fromJson | toJson | quote }}
      release:
        prefix: rabbitmq-
        labels:
          cozystack.io/ui: "true"
        chart:
          name: rabbitmq
          sourceRef:
            kind: HelmRepository
            name: cozystack-apps
            namespace: cozy-public
    - application:
        kind: Postgres
        singular: postgres
        plural: postgreses
        openAPISchema: {{ .Files.Get "openapi-schemas/postgres.json" | fromJson | toJson | quote }}
      release:
        prefix: postgres-
        labels:
          cozystack.io/ui: "true"
        chart:
          name: postgres
          sourceRef:
            kind: HelmRepository
            name: cozystack-apps
            namespace: cozy-public
    - application:
        kind: FerretDB
        singular: ferretdb
        plural: ferretdb
        openAPISchema: {{ .Files.Get "openapi-schemas/ferretdb.json" | fromJson | toJson | quote }}
      release:
        prefix: ferretdb-
        labels:
          cozystack.io/ui: "true"
        chart:
          name: ferretdb
          sourceRef:
            kind: HelmRepository
            name: cozystack-apps
            namespace: cozy-public
    - application:
        kind: Kafka
        singular: kafka
        plural: kafkas
        openAPISchema: {{ .Files.Get "openapi-schemas/kafka.json" | fromJson | toJson | quote }}
      release:
        prefix: kafka-
        labels:
          cozystack.io/ui: "true"
        chart:
          name: kafka
          sourceRef:
            kind: HelmRepository
            name: cozystack-apps
            namespace: cozy-public
    - application:
        kind: VMDisk
        plural: vmdisks
        singular: vmdisk
        openAPISchema: {{ .Files.Get "openapi-schemas/vm-disk.json" | fromJson | toJson | quote }}
      release:
        prefix: vm-disk-
        labels:
          cozystack.io/ui: "true"
        chart:
          name: vm-disk
          sourceRef:
            kind: HelmRepository
            name: cozystack-apps
            namespace: cozy-public
    - application:
        kind: VMInstance
        plural: vminstances
        singular: vminstance
        openAPISchema: {{ .Files.Get "openapi-schemas/vm-instance.json" | fromJson | toJson | quote }}
      release:
        prefix: vm-instance-
        labels:
          cozystack.io/ui: "true"
        chart:
          name: vm-instance
          sourceRef:
            kind: HelmRepository
            name: cozystack-apps
            namespace: cozy-public
    - application:
        kind: Monitoring
        plural: monitorings
        singular: monitoring
        openAPISchema: {{ .Files.Get "openapi-schemas/monitoring.json" | fromJson | toJson | quote }}
      release:
        prefix: ""
        labels:
          cozystack.io/ui: "true"
        chart:
          name: monitoring
          sourceRef:
            kind: HelmRepository
            name: cozystack-extra
            namespace: cozy-public
    - application:
        kind: Etcd
        plural: etcds
        singular: etcd
        openAPISchema: {{ .Files.Get "openapi-schemas/etcd.json" | fromJson | toJson | quote }}
      release:
        prefix: ""
        labels:
          cozystack.io/ui: "true"
        chart:
          name: etcd
          sourceRef:
            kind: HelmRepository
            name: cozystack-extra
            namespace: cozy-public
    - application:
        kind: Ingress
        plural: ingresses
        singular: ingress
        openAPISchema: {{ .Files.Get "openapi-schemas/ingress.json" | fromJson | toJson | quote }}
      release:
        prefix: ""
        labels:
          cozystack.io/ui: "true"
        chart:
          name: ingress
          sourceRef:
            kind: HelmRepository
            name: cozystack-extra
            namespace: cozy-public
    - application:
        kind: SeaweedFS
        plural: seaweedfses
        singular: seaweedfs
        openAPISchema: {{ .Files.Get "openapi-schemas/seaweedfs.json" | fromJson | toJson | quote }}
      release:
        prefix: ""
        labels:
          cozystack.io/ui: "true"
        chart:
          name: seaweedfs
          sourceRef:
            kind: HelmRepository
            name: cozystack-extra
            namespace: cozy-public
    - application:
        kind: BootBox
        plural: bootboxes
        singular: bootbox
        openAPISchema: {{ .Files.Get "openapi-schemas/bootbox.json" | fromJson | toJson | quote }}
      release:
        prefix: ""
        labels:
          cozystack.io/ui: "true"
        chart:
          name: bootbox
          sourceRef:
            kind: HelmRepository
            name: cozystack-extra
            namespace: cozy-public
    - application:
        kind: Info
        plural: infos
        singular: info
        openAPISchema: {{ .Files.Get "openapi-schemas/info.json" | fromJson | toJson | quote }}
      release:
        prefix: ""
        labels:
          cozystack.io/ui: "true"
        chart:
          name: info
          sourceRef:
            kind: HelmRepository
            name: cozystack-extra
            namespace: cozy-public
