apiVersion: cozystack.io/v1alpha1
kind: CozystackResourceDefinition
metadata:
  name: bucket
spec:
  application:
    kind: Bucket
    singular: bucket
    plural: buckets
    openAPISchema: |
      {{- .Files.Get "openapi-schemas/bucket.json" | fromJson | toJson | nindent 6 }}
  release:
    prefix: bucket-
    labels:
      cozystack.io/ui: "true"
    chart:
      name: bucket
      sourceRef:
        kind: HelmRepository
        name: cozystack-apps
        namespace: cozy-public
---
apiVersion: cozystack.io/v1alpha1
kind: CozystackResourceDefinition
metadata:
  name: clickhouse
spec:
  application:
    kind: ClickHouse
    singular: clickhouse
    plural: clickhouses
    openAPISchema: |
      {{- .Files.Get "openapi-schemas/clickhouse.json" | fromJson | toJson | nindent 6 }}
  release:
    prefix: clickhouse-
    labels:
      cozystack.io/ui: "true"
    chart:
      name: clickhouse
      sourceRef:
        kind: HelmRepository
        name: cozystack-apps
        namespace: cozy-public
---
apiVersion: cozystack.io/v1alpha1
kind: CozystackResourceDefinition
metadata:
  name: httpcache
spec:
  application:
    kind: HTTPCache
    singular: httpcache
    plural: httpcaches
    openAPISchema: |
      {{- .Files.Get "openapi-schemas/http-cache.json" | fromJson | toJson | nindent 6 }}
  release:
    prefix: http-cache-
    labels:
      cozystack.io/ui: "true"
    chart:
      name: http-cache
      sourceRef:
        kind: HelmRepository
        name: cozystack-apps
        namespace: cozy-public
---
apiVersion: cozystack.io/v1alpha1
kind: CozystackResourceDefinition
metadata:
  name: nats
spec:
  application:
    kind: NATS
    singular: nats
    plural: natses
    openAPISchema: |
      {{- .Files.Get "openapi-schemas/nats.json" | fromJson | toJson | nindent 6 }}
  release:
    prefix: nats-
    labels:
      cozystack.io/ui: "true"
    chart:
      name: nats
      sourceRef:
        kind: HelmRepository
        name: cozystack-apps
        namespace: cozy-public
---
apiVersion: cozystack.io/v1alpha1
kind: CozystackResourceDefinition
metadata:
  name: tcpbalancer
spec:
  application:
    kind: TCPBalancer
    singular: tcpbalancer
    plural: tcpbalancers
    openAPISchema: |
      {{- .Files.Get "openapi-schemas/tcp-balancer.json" | fromJson | toJson | nindent 6 }}
  release:
    prefix: tcp-balancer-
    labels:
      cozystack.io/ui: "true"
    chart:
      name: tcp-balancer
      sourceRef:
        kind: HelmRepository
        name: cozystack-apps
        namespace: cozy-public
---
apiVersion: cozystack.io/v1alpha1
kind: CozystackResourceDefinition
metadata:
  name: virtualmachine
spec:
  application:
    kind: VirtualMachine
    singular: virtualmachine
    plural: virtualmachines
    openAPISchema: |
      {{- .Files.Get "openapi-schemas/virtual-machine.json" | fromJson | toJson | nindent 6 }}
  release:
    prefix: virtual-machine-
    labels:
      cozystack.io/ui: "true"
    chart:
      name: virtual-machine
      sourceRef:
        kind: HelmRepository
        name: cozystack-apps
        namespace: cozy-public
---
apiVersion: cozystack.io/v1alpha1
kind: CozystackResourceDefinition
metadata:
  name: vpn
spec:
  application:
    kind: VPN
    singular: vpn
    plural: vpns
    openAPISchema: |
      {{- .Files.Get "openapi-schemas/vpn.json" | fromJson | toJson | nindent 6 }}
  release:
    prefix: vpn-
    labels:
      cozystack.io/ui: "true"
    chart:
      name: vpn
      sourceRef:
        kind: HelmRepository
        name: cozystack-apps
        namespace: cozy-public
---
apiVersion: cozystack.io/v1alpha1
kind: CozystackResourceDefinition
metadata:
  name: mysql
spec:
  application:
    kind: MySQL
    singular: mysql
    plural: mysqls
    openAPISchema: |
      {{- .Files.Get "openapi-schemas/mysql.json" | fromJson | toJson | nindent 6 }}
  release:
    prefix: mysql-
    labels:
      cozystack.io/ui: "true"
    chart:
      name: mysql
      sourceRef:
        kind: HelmRepository
        name: cozystack-apps
        namespace: cozy-public
---
apiVersion: cozystack.io/v1alpha1
kind: CozystackResourceDefinition
metadata:
  name: tenant
spec:
  application:
    kind: Tenant
    singular: tenant
    plural: tenants
    openAPISchema: |
      {{- .Files.Get "openapi-schemas/tenant.json" | fromJson | toJson | nindent 6 }}
  release:
    prefix: tenant-
    labels:
      cozystack.io/ui: "true"
    chart:
      name: tenant
      sourceRef:
        kind: HelmRepository
        name: cozystack-apps
        namespace: cozy-public
---
apiVersion: cozystack.io/v1alpha1
kind: CozystackResourceDefinition
metadata:
  name: kubernetes
spec:
  application:
    kind: Kubernetes
    singular: kubernetes
    plural: kuberneteses
    openAPISchema: |
      {{- .Files.Get "openapi-schemas/kubernetes.json" | fromJson | toJson | nindent 6 }}
  release:
    prefix: kubernetes-
    labels:
      cozystack.io/ui: "true"
    chart:
      name: kubernetes
      sourceRef:
        kind: HelmRepository
        name: cozystack-apps
        namespace: cozy-public
---
apiVersion: cozystack.io/v1alpha1
kind: CozystackResourceDefinition
metadata:
  name: redis
spec:
  application:
    kind: Redis
    singular: redis
    plural: redises
    openAPISchema: |
      {{- .Files.Get "openapi-schemas/redis.json" | fromJson | toJson | nindent 6 }}
  release:
    prefix: redis-
    labels:
      cozystack.io/ui: "true"
    chart:
      name: redis
      sourceRef:
        kind: HelmRepository
        name: cozystack-apps
        namespace: cozy-public
---
apiVersion: cozystack.io/v1alpha1
kind: CozystackResourceDefinition
metadata:
  name: rabbitmq
spec:
  application:
    kind: RabbitMQ
    singular: rabbitmq
    plural: rabbitmqs
    openAPISchema: |
      {{- .Files.Get "openapi-schemas/rabbitmq.json" | fromJson | toJson | nindent 6 }}
  release:
    prefix: rabbitmq-
    labels:
      cozystack.io/ui: "true"
    chart:
      name: rabbitmq
      sourceRef:
        kind: HelmRepository
        name: cozystack-apps
        namespace: cozy-public
---
apiVersion: cozystack.io/v1alpha1
kind: CozystackResourceDefinition
metadata:
  name: postgres
spec:
  application:
    kind: Postgres
    singular: postgres
    plural: postgreses
    openAPISchema: |
      {{- .Files.Get "openapi-schemas/postgres.json" | fromJson | toJson | nindent 6 }}
  release:
    prefix: postgres-
    labels:
      cozystack.io/ui: "true"
    chart:
      name: postgres
      sourceRef:
        kind: HelmRepository
        name: cozystack-apps
        namespace: cozy-public
---
apiVersion: cozystack.io/v1alpha1
kind: CozystackResourceDefinition
metadata:
  name: ferretdb
spec:
  application:
    kind: FerretDB
    singular: ferretdb
    plural: ferretdbs
    openAPISchema: |
      {{- .Files.Get "openapi-schemas/ferretdb.json" | fromJson | toJson | nindent 6 }}
  release:
    prefix: ferretdb-
    labels:
      cozystack.io/ui: "true"
    chart:
      name: ferretdb
      sourceRef:
        kind: HelmRepository
        name: cozystack-apps
        namespace: cozy-public
---
apiVersion: cozystack.io/v1alpha1
kind: CozystackResourceDefinition
metadata:
  name: kafka
spec:
  application:
    kind: Kafka
    singular: kafka
    plural: kafkas
    openAPISchema: |
      {{- .Files.Get "openapi-schemas/kafka.json" | fromJson | toJson | nindent 6 }}
  release:
    prefix: kafka-
    labels:
      cozystack.io/ui: "true"
    chart:
      name: kafka
      sourceRef:
        kind: HelmRepository
        name: cozystack-apps
        namespace: cozy-public
---
apiVersion: cozystack.io/v1alpha1
kind: CozystackResourceDefinition
metadata:
  name: vmdisk
spec:
  application:
    kind: VMDisk
    singular: vmdisk
    plural: vmdisks
    openAPISchema: |
      {{- .Files.Get "openapi-schemas/vm-disk.json" | fromJson | toJson | nindent 6 }}
  release:
    prefix: vm-disk-
    labels:
      cozystack.io/ui: "true"
    chart:
      name: vm-disk
      sourceRef:
        kind: HelmRepository
        name: cozystack-apps
        namespace: cozy-public
---
apiVersion: cozystack.io/v1alpha1
kind: CozystackResourceDefinition
metadata:
  name: vminstance
spec:
  application:
    kind: VMInstance
    singular: vminstance
    plural: vminstances
    openAPISchema: |
      {{- .Files.Get "openapi-schemas/vm-instance.json" | fromJson | toJson | nindent 6 }}
  release:
    prefix: vm-instance-
    labels:
      cozystack.io/ui: "true"
    chart:
      name: vm-instance
      sourceRef:
        kind: HelmRepository
        name: cozystack-apps
        namespace: cozy-public
---
apiVersion: cozystack.io/v1alpha1
kind: CozystackResourceDefinition
metadata:
  name: monitoring
spec:
  application:
    kind: Monitoring
    singular: monitoring
    plural: monitorings
    openAPISchema: |
      {{- .Files.Get "openapi-schemas/monitoring.json" | fromJson | toJson | nindent 6 }}
  release:
    prefix: ""
    labels:
      cozystack.io/ui: "true"
    chart:
      name: monitoring
      sourceRef:
        kind: HelmRepository
        name: cozystack-extra
        namespace: cozy-public
---
apiVersion: cozystack.io/v1alpha1
kind: CozystackResourceDefinition
metadata:
  name: etcd
spec:
  application:
    kind: Etcd
    singular: etcd
    plural: etcds
    openAPISchema: |
      {{- .Files.Get "openapi-schemas/etcd.json" | fromJson | toJson | nindent 6 }}
  release:
    prefix: ""
    labels:
      cozystack.io/ui: "true"
    chart:
      name: etcd
      sourceRef:
        kind: HelmRepository
        name: cozystack-extra
        namespace: cozy-public
---
apiVersion: cozystack.io/v1alpha1
kind: CozystackResourceDefinition
metadata:
  name: ingress
spec:
  application:
    kind: Ingress
    singular: ingress
    plural: ingresses
    openAPISchema: |
      {{- .Files.Get "openapi-schemas/ingress.json" | fromJson | toJson | nindent 6 }}
  release:
    prefix: ""
    labels:
      cozystack.io/ui: "true"
    chart:
      name: ingress
      sourceRef:
        kind: HelmRepository
        name: cozystack-extra
        namespace: cozy-public
---
apiVersion: cozystack.io/v1alpha1
kind: CozystackResourceDefinition
metadata:
  name: seaweedfs
spec:
  application:
    kind: SeaweedFS
    singular: seaweedfs
    plural: seaweedfses
    openAPISchema: |
      {{- .Files.Get "openapi-schemas/seaweedfs.json" | fromJson | toJson | nindent 6 }}
  release:
    prefix: ""
    labels:
      cozystack.io/ui: "true"
    chart:
      name: seaweedfs
      sourceRef:
        kind: HelmRepository
        name: cozystack-extra
        namespace: cozy-public
---
apiVersion: cozystack.io/v1alpha1
kind: CozystackResourceDefinition
metadata:
  name: bootbox
spec:
  application:
    kind: BootBox
    singular: bootbox
    plural: bootboxes
    openAPISchema: |
      {{- .Files.Get "openapi-schemas/bootbox.json" | fromJson | toJson | nindent 6 }}
  release:
    prefix: ""
    labels:
      cozystack.io/ui: "true"
    chart:
      name: bootbox
      sourceRef:
        kind: HelmRepository
        name: cozystack-extra
        namespace: cozy-public
---
apiVersion: cozystack.io/v1alpha1
kind: CozystackResourceDefinition
metadata:
  name: info
spec:
  application:
    kind: Info
    singular: info
    plural: infos
    openAPISchema: |
      {{- .Files.Get "openapi-schemas/info.json" | fromJson | toJson | nindent 6 }}
  release:
    prefix: ""
    labels:
      cozystack.io/ui: "true"
    chart:
      name: info
      sourceRef:
        kind: HelmRepository
        name: cozystack-extra
        namespace: cozy-public
