kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cozystack-api
rules:
- apiGroups: [""]
  resources: ["namespaces", "secrets"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "update", "patch", "delete"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations", "validatingwebhookconfigurations", "validatingadmissionpolicies", "validatingadmissionpolicybindings"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["flowcontrol.apiserver.k8s.io"]
  resources: ["prioritylevelconfigurations", "flowschemas"]
  verbs: ["list", "watch"]
- apiGroups: ["cozystack.io"]
  resources: ["*"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["helm.toolkit.fluxcd.io"]
  resources: ["*"]
  verbs: ["*"]
