apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tenantnamespaces-read
rules:
- apiGroups:
  - core.cozystack.io
  resources:
  - tenantnamespaces
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tenantnamespaces-read-authenticated
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tenantnamespaces-read
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
