name: Sync fork

on:
  workflow_dispatch:
  schedule:
  - cron: "03 23 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Sync and merge upstream repository with your current repository
        uses: dabreadman/sync-upstream-repo@v1.0.0.b
        with:
          upstream_repo: https://github.com/aenix-io/cozystack
          upstream_branch: main
          downstream_branch: main
          token: ${{ secrets.GITHUB_TOKEN }}
          # merge_args: 
          # push_args:
